import { Button } from "@starter/site-ui/primitives";
import { Columns3, Heart, ListPlus, Share2 } from "lucide-react";
import type { ReactNode } from "react";
import type { SessionCollectionGroupDto } from "@starter/site-ui/contracts";

export function SessionCollectionPageView({ kind, ready, groups, activeGroup, onGroupChange, shareControl, content }: { kind:"favorites"|"compare"; ready:boolean; groups:SessionCollectionGroupDto[]; activeGroup:string|null; onGroupChange:(key:string)=>void; shareControl?:ReactNode; content?:ReactNode }) {
  const favorites=kind==="favorites"; const title=favorites?"Избранное":"Сравнение"; const empty=favorites?"Вы пока не добавили объекты в избранное.":"Добавьте объекты в сравнение из каталога."; const showEmpty=ready&&!content; const showTabs=groups.length>0&&!showEmpty;
  return <main className="bg-[var(--surface-card)]"><section className="mx-auto max-w-site-frame px-5 pt-8 pb-12 lg:pt-12 lg:pb-16"><div className="border-b border-[var(--border)] pb-7 md:pb-8"><h1 className="text-lead font-bold leading-tight-copy tracking-heading text-[var(--text-primary)] md:text-heading-small lg:text-heading-compact">{title}</h1>{!ready?<p className="mt-5 text-body font-medium text-[var(--text-muted)]">Загрузка…</p>:showTabs?<div className="mt-5 flex items-baseline justify-between gap-4 md:mt-6"><nav className="flex min-w-0 flex-wrap items-baseline gap-x-5 gap-y-2.5 md:gap-x-6" aria-label="Типы в подборке">{groups.map((group)=>{const active=group.key===activeGroup;return <Button variant="plain" key={group.key} type="button" onClick={()=>onGroupChange(group.key)} className={`inline-flex items-baseline gap-0.5 text-body-compact font-semibold leading-flat transition md:text-body-large ${active?"text-[var(--text-primary)]":"text-[var(--session-collection-page-content-muted)] hover:text-[var(--text-secondary)]"}`} aria-pressed={active}><span>{group.label}</span><sup className="text-overline font-bold tabular-nums md:text-caption">{group.count}</sup></Button>;})}</nav>{shareControl}</div>:<p className="mt-5 text-body font-medium text-[var(--text-muted)]">{empty}</p>}</div>
    {!ready?<div className="mt-6 min-h-55 animate-pulse rounded-lg bg-[var(--session-collection-page-surface-control)]" aria-hidden/>:showEmpty?<EmptyState favorites={favorites}/>:content}
  </section></main>;
}

function EmptyState({favorites}:{favorites:boolean}){return <div className="mt-6 mb-4 rounded-lg border border-[var(--border)] bg-[var(--surface-card)] px-5 py-6 md:mb-6 md:px-7 md:py-7 lg:py-8"><div className="max-w-none"><div className="min-w-0"><p className="text-caption font-bold uppercase tracking-overline-compact text-[var(--accent)]">Как работает {favorites?"избранное":"сравнение"}</p><h2 className="mt-2 text-balance text-body-large font-bold leading-tight-copy text-[var(--text-primary)] md:text-body-highlight">{favorites?"Соберите подборку и отправьте ее одной ссылкой":"Добавьте объекты и сравните их в одной таблице"}</h2></div><div className="mt-5 grid gap-4 md:mt-6 md:grid-cols-2 md:gap-x-8 md:gap-y-5 lg:grid-cols-[minmax(0,0.92fr)_minmax(0,1.08fr)] lg:gap-x-10 xl:gap-x-12">{favorites?<><Hint icon={<Heart className="size-4"/>} desktop={<>Сердечко добавляет объект в подборку и держит его под рукой,<br/>пока вы выбираете лучший вариант.</>} mobile="Сердечко добавляет объект в подборку и держит его под рукой, пока вы выбираете лучший вариант."/><Hint icon={<Share2 className="size-4"/>} desktop={<>Кнопка «Поделиться» создаёт постоянную ссылку, которую можно<br/>сразу отправить в мессенджере или скопировать.</>} mobile="Кнопка «Поделиться» создаёт постоянную ссылку, которую можно сразу отправить в мессенджере или скопировать."/></>:<><Hint icon={<ListPlus className="size-4"/>} desktop={<>Кнопка «Сравнить» находится в карточке объекта и добавляет<br/>варианты в этот раздел для детального сопоставления.</>} mobile="Кнопка «Сравнить» находится в карточке объекта и добавляет варианты в этот раздел для детального сопоставления."/><Hint icon={<Columns3 className="size-4"/>} desktop={<>Сравнение собирает цену, площадь, этаж и другие параметры<br/>в табличную форму, чтобы различия были видны сразу.</>} mobile="Сравнение собирает цену, площадь, этаж и другие параметры в табличную форму, чтобы различия были видны сразу."/></>}</div></div></div>;}
function Hint({icon,desktop,mobile}:{icon:ReactNode;desktop:ReactNode;mobile:string}){return <div className="flex items-start gap-2.5 md:gap-3"><span className="mt-0.5 shrink-0 text-[var(--accent)]" aria-hidden>{icon}</span><p className="text-body leading-step-copy text-[var(--text-secondary)] md:text-support md:leading-step-body lg:text-body lg:leading-step-copy"><span className="hidden lg:inline">{desktop}</span><span className="lg:hidden">{mobile}</span></p></div>;}
