allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
overrides:
  '@esbuild-kit/core-utils>esbuild': 0.27.1
  dompurify: 3.4.13
patchedDependencies:
  payload@3.88.0: patches/payload@3.88.0.patch
  '@payloadcms/next@3.88.0': patches/@payloadcms__next@3.88.0.patch
