allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - '@sentry/browser-utils@10.73.0'
  - '@sentry/browser@10.73.0'
  - '@sentry/core@10.73.0'
  - '@sentry/feedback@10.73.0'
  - '@sentry/nextjs@10.73.0'
  - '@sentry/node-core@10.73.0'
  - '@sentry/node@10.73.0'
  - '@sentry/opentelemetry@10.73.0'
  - '@sentry/react@10.73.0'
  - '@sentry/replay-canvas@10.73.0'
  - '@sentry/replay@10.73.0'
  - '@sentry/server-utils@10.73.0'
  - '@sentry/vercel-edge@10.73.0'
overrides:
  '@esbuild-kit/core-utils>esbuild': 0.27.1
  dompurify: 3.4.13
patchedDependencies:
  payload@3.88.0: patches/payload@3.88.0.patch
  '@payloadcms/next@3.88.0': patches/@payloadcms__next@3.88.0.patch
