"use client";

import { Building2, ChevronLeft, ChevronRight, ExternalLink, Trash2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { SessionCollectionItemDto } from "@starter/site-contracts";
import type { SiteImageRenderer, SiteLinkRenderer } from "../lib/adapters";

export function CompareTableView({ items, onRemove, linkRenderer: LinkRenderer, imageRenderer: ImageRenderer }: { items: SessionCollectionItemDto[]; onRemove: (id:string)=>void; linkRenderer: SiteLinkRenderer; imageRenderer: SiteImageRenderer }) {
  const scrollRef=useRef<HTMLDivElement>(null); const [onlyDifferences,setOnlyDifferences]=useState(false); const [left,setLeft]=useState(false); const [right,setRight]=useState(false); const [compact,setCompact]=useState(false);
  useEffect(()=>{const media=window.matchMedia("(max-width: 1023px)");const sync=()=>setCompact(media.matches);sync();media.addEventListener("change",sync);return()=>media.removeEventListener("change",sync);},[]);
  const labelWidth=compact?120:176; const columnWidth=compact?200:244; const columns=`${labelWidth}px repeat(${items.length}, minmax(${columnWidth}px, ${columnWidth}px))`;
  const rows=useMemo<CompareRow[]>(()=>[
    {label:"Стоимость",resolve:(item)=>formatPrice(item.price)}, {label:"Цена за м²",resolve:formatMeterPrice}, {label:"Адрес",resolve:(item)=>item.address}, {label:"Количество комнат",resolve:(item)=>item.rooms?String(item.rooms):"не указано"}, {label:"Общая площадь",resolve:(item)=>formatArea(item.area)}, {label:"Жилая",resolve:(item)=>formatArea(item.areaLiving)}, {label:"Кухня",resolve:(item)=>formatArea(item.areaKitchen)}, {label:"Этаж",resolve:formatFloor}, {label:"Ремонт",resolve:(item)=>item.renovation??"не указано"}, {label:"Материал постройки",resolve:(item)=>item.buildingType??"не указано"}, {label:"Год постройки",resolve:(item)=>item.builtYear?String(item.builtYear):"не указано"}, {label:"ID объекта",resolve:(item)=>item.objectCode??item.id},
  ],[]);
  const visibleRows=onlyDifferences&&items.length>1?rows.filter((row)=>different(items,row.resolve)):rows;
  useEffect(()=>{const element=scrollRef.current;if(!element)return;const sync=()=>{const max=element.scrollWidth-element.clientWidth;setLeft(element.scrollLeft>8);setRight(element.scrollLeft<max-8);};sync();element.addEventListener("scroll",sync,{passive:true});window.addEventListener("resize",sync);return()=>{element.removeEventListener("scroll",sync);window.removeEventListener("resize",sync);};},[items.length,onlyDifferences,compact]);
  const scroll=(direction:"left"|"right")=>scrollRef.current?.scrollBy({left:direction==="right"?columnWidth+40:-(columnWidth+40),behavior:"smooth"});
  return <section className="mt-5 overflow-hidden rounded-lg border border-[var(--border)] bg-white shadow-[0_18px_52px_rgba(0,0,0,0.05)] lg:mt-6">
    <header className="grid gap-4 border-b border-[var(--border)] bg-[var(--surface-card-soft)] px-4 py-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-center md:px-5"><div><p className="text-sm font-extrabold leading-5 text-[var(--text-primary)]">{compareLabel(items)}</p><p className="mt-1 text-xs font-medium leading-5 text-[var(--text-muted)]">{compact?"Листайте объекты вправо. Слева закреплены названия параметров.":"Сравнивайте фото, цену и ключевые параметры. Доска рассчитана на комфортную работу с подборкой до 12 объектов."}</p></div><label className="inline-flex min-h-10 items-start gap-2 text-xs font-semibold leading-5 text-[var(--text-secondary)] md:items-center"><input type="checkbox" checked={onlyDifferences} onChange={(event)=>setOnlyDifferences(event.target.checked)} className="mt-1 size-4 rounded border-[#D0D0CD] accent-[var(--accent)] md:mt-0"/><span>Показывать только отличия<span className="block font-medium text-[var(--text-muted)]">Скроем совпадающие строки</span></span></label></header>
    <div className="relative">{left?<button type="button" onClick={()=>scroll("left")} className="absolute z-30 hidden size-11 items-center justify-center rounded-lg border border-[var(--border)] bg-white text-[var(--text-primary)] shadow-[0_10px_26px_rgba(0,0,0,0.14)] transition hover:border-[var(--accent)] hover:text-[var(--accent)] lg:flex" style={{left:labelWidth+12,top:118}} aria-label="Прокрутить сравнение влево"><ChevronLeft className="size-5" aria-hidden/></button>:null}{right?<button type="button" onClick={()=>scroll("right")} className="absolute right-4 top-[118px] z-30 hidden size-11 items-center justify-center rounded-lg border border-[var(--border)] bg-white text-[var(--text-primary)] shadow-[0_10px_26px_rgba(0,0,0,0.14)] transition hover:border-[var(--accent)] hover:text-[var(--accent)] lg:flex" aria-label="Прокрутить сравнение вправо"><ChevronRight className="size-5" aria-hidden/></button>:null}
      <div ref={scrollRef} className="overflow-x-auto overscroll-x-contain [-webkit-overflow-scrolling:touch]"><div className="min-w-max"><div className="grid border-b border-[var(--border)]" style={{gridTemplateColumns:columns}}><div className="sticky left-0 z-20 bg-white px-3 py-4 text-sm font-extrabold text-[var(--text-secondary)] shadow-[8px_0_18px_rgba(255,255,255,0.92)] md:px-5">Объекты<span className="mt-1 block text-xs font-medium text-[var(--text-muted)]">Фото и стоимость</span></div>{items.map((item)=><ObjectCard key={item.id} item={item} compact={compact} onRemove={()=>onRemove(item.id)} linkRenderer={LinkRenderer} imageRenderer={ImageRenderer}/>)}</div>{visibleRows.length?visibleRows.map((row)=><div key={row.label} className="grid border-b border-[var(--surface-muted)] last:border-b-0" style={{gridTemplateColumns:columns}}><div className="sticky left-0 z-20 bg-white px-3 py-3 text-sm font-extrabold leading-5 text-[var(--text-secondary)] shadow-[8px_0_18px_rgba(255,255,255,0.92)] md:px-5">{row.label}</div>{items.map((item)=><div key={`${item.id}-${row.label}`} className="px-3 py-3 text-sm font-medium leading-5 text-[var(--text-primary)] md:px-4">{row.resolve(item)}</div>)}</div>):<div className="grid" style={{gridTemplateColumns:columns}}><div className="sticky left-0 z-20 bg-white px-3 py-4 text-sm font-extrabold text-[var(--text-secondary)] shadow-[8px_0_18px_rgba(255,255,255,0.92)] md:px-5">Отличия</div><div className="px-3 py-4 text-sm font-medium text-[var(--text-muted)] md:px-4" style={{gridColumn:"2 / -1"}}>По базовым параметрам объекты совпадают.</div></div>}</div></div>
    </div>
  </section>;
}

function ObjectCard({item,onRemove,compact,linkRenderer:LinkRenderer,imageRenderer:ImageRenderer}:{item:SessionCollectionItemDto;onRemove:()=>void;compact:boolean;linkRenderer:SiteLinkRenderer;imageRenderer:SiteImageRenderer}){return <article className={`relative ${compact?"px-2.5 py-3":"px-3 py-4"}`}><button type="button" onClick={onRemove} className="absolute right-3 top-5 z-10 inline-flex size-8 items-center justify-center rounded-lg bg-[#18181A]/72 text-white backdrop-blur-sm transition hover:bg-[var(--accent)] md:right-5 md:top-6" aria-label="Убрать из сравнения"><Trash2 className="size-4" aria-hidden/></button><LinkRenderer href={item.path} className="group block"><div className="relative aspect-[4/3] overflow-hidden rounded-lg bg-[var(--surface-muted)]">{item.image?<ImageRenderer src={item.image} alt={item.title} fill unoptimized={item.image.startsWith("http")} sizes="244px" className="object-cover transition duration-500 group-hover:scale-[1.03]"/>:<span className="grid h-full place-items-center text-[var(--text-muted)]"><Building2 className="size-8" aria-hidden/></span>}</div><p className="mt-3 text-[1.05rem] font-extrabold leading-none tabular-nums text-[var(--text-primary)]">{formatPrice(item.price)}</p><p className="mt-1 text-xs font-semibold leading-5 text-[var(--text-muted)]">{formatMeterPrice(item)}</p><h2 className="mt-2 line-clamp-2 text-sm font-extrabold leading-5 text-[var(--text-primary)] transition group-hover:text-[var(--accent)]">{item.title}</h2><span className="mt-3 inline-flex min-h-9 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-xs font-bold text-[var(--text-secondary)] transition group-hover:border-[var(--accent)] group-hover:text-[var(--accent)]">Открыть объект<ExternalLink className="size-3.5" aria-hidden/></span></LinkRenderer></article>;}
type CompareRow={label:string;resolve:(item:SessionCollectionItemDto)=>string};
function formatPrice(value:number|null|undefined){return value===null||value===undefined?"Цена по запросу":new Intl.NumberFormat("ru-RU",{style:"currency",currency:"RUB",maximumFractionDigits:0}).format(value);}
function formatArea(value?:number|null){return value?`${new Intl.NumberFormat("ru-RU",{maximumFractionDigits:1}).format(value)} м²`:"не указано";}
function formatFloor(item:SessionCollectionItemDto){return item.floor?`${item.floor} из ${item.floorsTotal??"-"}`:"не указано";}
function formatMeterPrice(item:SessionCollectionItemDto){return item.price&&item.area?`${formatPrice(Math.round(item.price/item.area))}/м²`:"не указано";}
function different(items:SessionCollectionItemDto[],resolve:(item:SessionCollectionItemDto)=>string){return new Set(items.map((item)=>resolve(item).trim().toLowerCase())).size>1;}
function compareLabel(items:SessionCollectionItemDto[]){const keys=new Set(items.map((item)=>item.categoryKey));if(keys.size!==1)return `Объекты ${items.length}`;const key=items[0]?.categoryKey;const label=key==="flat"||key==="room"?"Квартиры":key==="house"?"Дома":key==="land"?"Участки":key==="commercial"?"Коммерция":key==="construction"?"Строительство":key==="new_building"?"Новостройки":"Объекты";return `${label} ${items.length}`;}
