import { ArrowLeft, ArrowRight, Building2 } from "lucide-react";
import type { ReactNode } from "react";
import type { SitemapListingPageDto } from "@starter/site-contracts";
import type { SiteLinkRenderer } from "../lib/adapters";

export function HtmlSitemapListingView({ page, breadcrumbs, linkRenderer: LinkRenderer }: { page: SitemapListingPageDto; breadcrumbs: ReactNode; linkRenderer: SiteLinkRenderer }) {
  const totalPages=Math.max(1,Math.ceil(page.total/page.pageSize)); const title=page.kind==="objects"?"Актуальные объекты недвижимости":"Резерв объектов"; const basePath=`/sitemap/${page.kind}`;
  return <main className="bg-[var(--palette-f5f5f3)] text-[var(--palette-1c1b1f)]"><header className="border-b border-[var(--palette-dededa)] bg-white"><div className="mx-auto max-w-[1180px] px-5 py-9 md:px-8 md:py-12">{breadcrumbs}<LinkRenderer href="/sitemap" className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--palette-6a676b)] hover:text-[var(--accent)]"><ArrowLeft className="size-4" aria-hidden /> Карта сайта</LinkRenderer><h1 className="mt-4 text-[30px] font-extrabold leading-tight md:text-[38px]">{title}</h1><p className="mt-3 text-sm text-[var(--palette-666267)]">Страница {page.page} из {totalPages}. Всего объектов: {page.total}.</p></div></header><section className="mx-auto max-w-[1180px] px-5 py-8 md:px-8 md:py-12"><div className="grid gap-px overflow-hidden rounded-lg border border-[var(--palette-dededa)] bg-[var(--palette-dededa)] sm:grid-cols-2 lg:grid-cols-3">{page.items.map((item)=><LinkRenderer key={item.id} href={`/obekty/${item.slug}`} className="group flex min-h-[88px] gap-3 bg-white p-4 transition hover:bg-[var(--palette-fafaf8)]"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-[var(--palette-f3ecec)] text-[var(--accent)]"><Building2 className="size-4" aria-hidden /></span><span className="min-w-0 text-sm font-semibold leading-5 text-[var(--palette-343136)] group-hover:text-[var(--accent)]">{item.title}</span></LinkRenderer>)}</div><nav className="mt-6 flex flex-wrap items-center justify-center gap-2" aria-label="Пагинация карты сайта">{page.page>1?<LinkRenderer href={`${basePath}/${page.page-1}`} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[var(--palette-d3d3cf)] bg-white px-4 text-sm font-bold"><ArrowLeft className="size-4" aria-hidden /> Назад</LinkRenderer>:null}{buildPagination(page.page,totalPages).map((item,index)=>item==="ellipsis"?<span key={`ellipsis-${index}`} className="grid min-h-11 min-w-11 place-items-center text-sm text-[var(--palette-6a676b)]">…</span>:<LinkRenderer key={item} href={`${basePath}/${item}`} ariaCurrent={item===page.page?"page":undefined} className={`grid min-h-11 min-w-11 place-items-center rounded-lg border px-3 text-sm font-bold ${item===page.page?"border-[var(--palette-1f1e21)] bg-[var(--palette-1f1e21)] text-white":"border-[var(--palette-d3d3cf)] bg-white text-[var(--palette-1f1e21)]"}`}>{item}</LinkRenderer>)}{page.page<totalPages?<LinkRenderer href={`${basePath}/${page.page+1}`} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[var(--palette-1f1e21)] px-4 text-sm font-bold text-white">Далее <ArrowRight className="size-4" aria-hidden /></LinkRenderer>:null}</nav></section></main>;
}
function buildPagination(page:number,totalPages:number):Array<number|"ellipsis">{const pages=new Set([1,totalPages,page-2,page-1,page,page+1,page+2]);const visible=[...pages].filter((item)=>item>=1&&item<=totalPages).sort((a,b)=>a-b);const result:Array<number|"ellipsis">=[];visible.forEach((item,index)=>{if(index>0&&item-visible[index-1]!>1)result.push("ellipsis");result.push(item);});return result;}
