import { Building2, Check, DraftingCompass, FileCheck2, Handshake, KeyRound, Landmark, SearchCheck, UserMinus, Workflow, type LucideIcon } from "lucide-react";
import type { ReactNode } from "react";

const APPROACH_ITEMS = [
  { title: "Специализация только на недвижимости", description: "Работаем с квартирами, домами, участками и коммерцией. Не ведём уголовные дела, семейные споры и другие направления.", Icon: Building2 },
  { title: "Понимание специфики региона", description: "Приводим документы украинского образца в соответствие с законодательством РФ. Знаем нюансы регистрации в Росреестре и работы с границами участков.", Icon: Landmark },
  { title: "Связка с отделом продаж", description: "Юрист видит всю картину сделки. Проверяем не только бумаги, но и то, можно ли объект реально продать или купить.", Icon: Workflow },
  { title: "Фиксация стоимости в договоре", description: "Согласовываем объём работ и стоимость до начала. Никаких скрытых платежей или дополнительных услуг в процессе.", Icon: FileCheck2 },
] as const;
const INHERITANCE_CASES = ["Восстанавливаем пропущенные сроки принятия наследства через суд", "Приводим документы украинского образца в соответствие с РФ", "Решаем споры между наследниками и выделяем реальные доли", "Подтверждаем фактическое принятие наследства при отсутствии бумаг", "Признаем право, если собственник умер давно"] as const;
const LEGAL_SERVICES: Array<{ title: string; description: string; Icon: LucideIcon }> = [
  { title: "Сопровождение сделок купли-продажи", description: "Проверяем историю объекта, готовим договоры, контролируем безопасные расчеты.", Icon: Handshake },
  { title: "Регистрация права собственности", description: "Приводим документы старого образца в соответствие с законодательством РФ, оформляем через Росреестр.", Icon: KeyRound },
  { title: "Узаконивание перепланировок", description: "Готовим технические заключения, представляем ваши интересы в администрации или суде.", Icon: DraftingCompass },
  { title: "Снятие с регистрации через суд", description: "Выписываем бывших супругов или непроживающих лиц для юридически чистой продажи объекта.", Icon: UserMinus },
  { title: "Экспресс-аудит документов перед покупкой", description: "Находим скрытые риски за один день, чтобы вы не потеряли задаток.", Icon: SearchCheck },
];
const PROCESS_STEPS = [
  { title: "Заявка или звонок", description: "Кратко описываете ситуацию. Первая консультация по телефону — бесплатно." },
  { title: "Анализ документов", description: "Проверяем право собственности, сроки, возможные риски и расхождения." },
  { title: "План и смета", description: "Фиксируем точную стоимость и сроки в договоре до начала любых работ." },
  { title: "Реализация", description: "Готовим документы и представляем ваши интересы в МФЦ, администрации или суде." },
] as const;

export type LawyerPageViewProps = {
  expert?: { fullName: string; position: string; portrait: ReactNode };
  employeeCards: readonly ReactNode[];
  servicesGallery: ReactNode;
  consultationForm: ReactNode;
  faq: ReactNode;
};

export function LawyerPageView({ expert, employeeCards, servicesGallery, consultationForm, faq }: LawyerPageViewProps) {
  return <>
    <section className="bg-[var(--palette-f9fafb)] py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-approach-title"><div className="mx-auto max-w-site-frame px-5"><h2 id="lawyer-approach-title" className="max-w-[1040px] text-[24px] font-semibold leading-[1.1] tracking-[-0.03em] text-[var(--text-primary)] sm:text-[clamp(24px,1.8vw,30px)]"><span className="lg:hidden">Сопровождаем сделки в Краснодаре: проверяем документы до выхода на договор</span><span className="hidden lg:block"><span className="block">Сопровождаем сделки в Краснодаре:</span><span className="block">проверяем документы до выхода на договор</span></span></h2><div className="mt-9 grid overflow-hidden rounded-xl border border-[var(--border)] bg-white sm:mt-11 sm:grid-cols-2">{APPROACH_ITEMS.map((item,index)=><article key={item.title} className={`grid min-h-[210px] grid-cols-[44px_1fr] gap-4 p-5 sm:p-7 ${index%2===0?"sm:border-r":""} ${index<3?"border-b":""} ${index>=2?"sm:border-b-0":""} border-[var(--border)]`}><span className="flex size-11 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><item.Icon className="size-[19px]" strokeWidth={1.6} aria-hidden /></span><div><h3 className="text-[17px] font-semibold leading-snug text-[var(--text-primary)]">{item.title}</h3><p className="mt-3 text-[14px] leading-6 text-[var(--palette-5e5a5f)]">{item.description}</p></div></article>)}</div></div></section>
    <section className="bg-white py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-inheritance-title"><div className={`mx-auto grid max-w-site-frame gap-8 px-5 ${expert?"lg:grid-cols-[minmax(320px,0.72fr)_minmax(0,1.28fr)] lg:items-stretch lg:gap-14":"lg:max-w-[900px]"}`}>{expert?<div className="relative min-h-[420px] overflow-hidden rounded-xl bg-[var(--palette-f5f6f6)] sm:min-h-[560px] lg:min-h-[620px]">{expert.portrait}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 via-black/35 to-transparent px-6 pb-6 pt-24 text-white"><p className="text-lg font-semibold">{expert.fullName}</p><p className="mt-1 text-sm text-white/75">{expert.position}</p></div></div>:null}<div className="flex flex-col justify-center"><h2 id="lawyer-inheritance-title" className="max-w-[820px] text-[26px] font-semibold leading-[1.12] tracking-[-0.03em] text-[var(--text-primary)] sm:text-[clamp(28px,2.4vw,38px)]">Признаем наследство через суд, если нотариус отказал из-за сроков или старых документов</h2><ul className="mt-8 border-y border-[var(--border)]">{INHERITANCE_CASES.map((item,index)=><li key={item} className={`flex min-h-16 items-center gap-3 py-4 text-[15px] font-medium leading-6 text-[var(--text-primary)] ${index<INHERITANCE_CASES.length-1?"border-b border-[var(--border)]":""}`}><Check className="size-4 shrink-0 text-[var(--accent)]" strokeWidth={1.8} aria-hidden />{item}</li>)}</ul><button type="button" data-request-modal data-request-modal-title="Получить консультацию юриста по недвижимости" data-request-modal-source="corporate:yurist:inheritance" data-request-modal-form-type="legal_consultation" className="mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-lg bg-[var(--accent)] px-6 text-sm font-semibold text-white transition hover:bg-[var(--accent-hover)] sm:w-fit">Оценить шансы по наследству</button></div></div></section>
    {employeeCards.length?<section className="bg-[var(--palette-f9fafb)] py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-team-title"><div className="mx-auto max-w-site-frame px-5"><h2 id="lawyer-team-title" className="text-[24px] font-semibold leading-[1.1] tracking-[-0.03em] text-[var(--text-primary)] sm:text-[clamp(24px,1.8vw,30px)]">Юридический отдел агентства недвижимости в Краснодаре</h2><p className="mt-4 max-w-[760px] text-[16px] leading-7 text-[var(--palette-5e5a5f)]">Руководитель отдела отвечает за стандарты проверки, а юристы ведут наследство, сделки и регистрацию.</p><div className="-mx-5 mt-9 flex snap-x snap-mandatory gap-4 overflow-x-auto px-5 pb-3 sm:mx-0 sm:grid sm:grid-cols-2 sm:overflow-visible sm:px-0 lg:grid-cols-4">{employeeCards.map((card,index)=><div key={index} className="min-w-[82vw] snap-start sm:min-w-0">{card}</div>)}<div className="min-w-[82vw] snap-start sm:min-w-0"><article className="flex h-full flex-col overflow-hidden rounded-lg bg-[var(--palette-24354b)] text-white"><div className="relative flex aspect-[4/3.35] items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_72%_22%,rgba(255,255,255,0.18),transparent_34%),linear-gradient(145deg,var(--palette-324a66)_0%,var(--palette-24354b)_58%,var(--palette-172536)_100%)]"><div className="absolute -right-10 -top-12 size-40 rounded-full border border-white/10"/><div className="absolute -bottom-16 -left-8 size-48 rounded-full border border-white/10"/><div className="flex size-20 items-center justify-center rounded-full border border-white/20 bg-white/10 backdrop-blur-sm"><FileCheck2 className="size-9 text-white" strokeWidth={1.35} aria-hidden /></div></div><div className="flex flex-1 flex-col p-5 sm:p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.1em] text-white/65">Консультация юриста</p><h3 className="mt-2 text-lg font-semibold leading-6">Нужна консультация?</h3><p className="mt-3 text-sm leading-6 text-white/72">Разберём документы и подскажем следующий шаг.</p><button type="button" data-request-modal data-request-modal-title="Получить консультацию юриста по недвижимости" data-request-modal-source="corporate:yurist:team" data-request-modal-form-type="legal_consultation" className="mt-auto inline-flex min-h-11 items-center justify-center rounded-lg bg-white px-4 text-sm font-semibold text-[var(--palette-24354b)] transition hover:bg-[var(--palette-f1f3f5)]">Получить консультацию</button></div></article></div></div><p className="mt-7 border-t border-[var(--border)] pt-6 text-[15px] font-medium leading-6 text-[var(--text-secondary)]">Юридический отдел работает в связке с отделом продаж. Проверяем не только документы, но и то, можно ли объект реально продать или купить.</p></div></section>:null}
    <section className="bg-white py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-services-title"><div className="mx-auto grid max-w-site-frame gap-10 px-5 lg:grid-cols-[minmax(320px,0.72fr)_minmax(0,1.28fr)] lg:items-start lg:gap-14">{servicesGallery}<div><h2 id="lawyer-services-title" className="max-w-[820px] text-[24px] font-semibold leading-[1.1] tracking-[-0.03em] text-[var(--text-primary)] sm:text-[clamp(24px,1.8vw,30px)]"><span className="lg:hidden">Решаем юридические задачи, которые тормозят покупку, продажу или регистрацию права</span><span className="hidden lg:block"><span className="block">Решаем юридические задачи, которые тормозят</span><span className="block">покупку, продажу или регистрацию права</span></span></h2><div className="mt-8 border-t border-[var(--palette-e5e7eb)]">{LEGAL_SERVICES.map((service,index)=><article key={service.title} className="border-b border-[var(--palette-e5e7eb)] py-6 sm:py-7"><div className="flex items-start gap-4"><service.Icon className="mt-0.5 size-6 shrink-0 text-[var(--palette-24354b)]" strokeWidth={1.5} aria-hidden /><div><h3 className="text-[17px] font-semibold leading-snug text-[var(--text-primary)]">{service.title}</h3><p className="mt-2 text-[14px] leading-6 text-[var(--palette-5e5a5f)]">{service.description}</p></div></div><span className="sr-only">{index+1}</span></article>)}</div></div></div></section>
    <section className="bg-[var(--palette-f9fafb)] py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-process-title"><div className="mx-auto max-w-site-frame px-5"><h2 id="lawyer-process-title" className="mx-auto max-w-[880px] text-center text-[24px] font-semibold leading-[1.1] tracking-[-0.03em] text-[var(--text-primary)] sm:text-[clamp(24px,1.8vw,30px)]">Как проходит работа с юристом: от звонка до получения документов</h2><ol className="relative mt-12 grid gap-9 before:absolute before:bottom-4 before:left-[23px] before:top-4 before:w-px before:bg-[var(--palette-d7dde3)] lg:grid-cols-4 lg:gap-8 lg:before:bottom-auto lg:before:left-0 lg:before:right-0 lg:before:top-[25px] lg:before:h-px lg:before:w-auto">{PROCESS_STEPS.map((step,index)=><li key={step.title} className="relative grid grid-cols-[48px_minmax(0,1fr)] gap-5 lg:block"><span className="relative z-10 flex h-[50px] items-center bg-[var(--palette-f9fafb)] pr-2 text-[32px] font-light leading-none tracking-[-0.04em] text-[var(--palette-24354b)] lg:w-fit lg:px-3 lg:first:pl-0">{String(index+1).padStart(2,"0")}</span><div className="pt-1 lg:pt-0"><h3 className="text-lg font-semibold leading-snug text-[var(--text-primary)] lg:mt-7">{step.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--palette-5e5a5f)]">{step.description}</p></div></li>)}</ol></div></section>
    <section id="lawyer-consultation" className="bg-[var(--palette-f9fafb)] py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-consultation-title"><div className="mx-auto max-w-site-frame px-5"><div className="w-full rounded-2xl border border-[var(--palette-e5e7eb)] bg-white px-5 py-9 text-center shadow-[0_18px_50px_rgba(17,24,39,0.06)] sm:px-10 sm:py-12 lg:px-16 lg:py-14"><h2 id="lawyer-consultation-title" className="mx-auto max-w-[900px] text-[24px] font-semibold leading-[1.13] tracking-[-0.035em] text-[var(--palette-111827)] sm:text-[clamp(28px,2vw,34px)]">Оставьте заявку — юрист перезвонит в течение 15 минут и оценит вашу ситуацию</h2><p className="mx-auto mt-4 max-w-[760px] text-[15px] leading-7 text-[var(--palette-4b5563)]">Первая консультация по телефону бесплатно. Расскажите кратко о ситуации, и мы скажем, можно ли решить вопрос без суда или нужна подготовка документов.</p><div className="mx-auto mt-8 max-w-[600px] text-left text-[var(--palette-111827)] [&>form]:mt-0">{consultationForm}</div></div></div></section>
    <section id="lawyer-faq" className="bg-white py-12 sm:py-16 lg:py-[88px]" aria-labelledby="lawyer-faq-title"><div className="mx-auto max-w-site-frame px-5"><h2 id="lawyer-faq-title" className="mb-9 text-[24px] font-semibold leading-[1.1] tracking-[-0.03em] text-[var(--text-primary)] sm:text-[clamp(24px,1.8vw,30px)]">Отвечаем на вопросы, которые чаще всего возникают до заявки</h2>{faq}</div></section>
  </>;
}
