import { Star } from "lucide-react";
import type { EmployeeReviewsPageDto } from "@starter/site-contracts";
import type { SiteImageRenderer, SiteLinkRenderer } from "../../lib/adapters";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card } from "../../components/ui/card";

type Props = { page: EmployeeReviewsPageDto; placeholderImage: string; linkRenderer: SiteLinkRenderer; imageRenderer: SiteImageRenderer };

export function EmployeeReviewsView({ page, placeholderImage, linkRenderer: LinkRenderer, imageRenderer: ImageRenderer }: Props) {
  return (
    <section id="employee-reviews" className="scroll-mt-28 border-t border-[var(--border)] bg-[var(--surface-card-soft)]">
      <div className="mx-auto max-w-site-frame px-5 py-12 md:px-8 md:py-16 lg:px-10">
        <header className="flex flex-col gap-3 border-b border-[var(--border)] pb-6 md:flex-row md:items-end md:justify-between md:gap-8"><div><h2 className="text-section-title font-semibold leading-section-title text-[var(--text-primary)]">Отзывы о специалистах агентства недвижимости</h2><p className="mt-3 max-w-2xl text-body-compact leading-step-relaxed text-[var(--text-secondary)]">Отзывы клиентов о работе специалистов агентства недвижимости.</p></div>{page.preview ? <Badge variant="soft" className="shrink-0 rounded-lg px-3 py-2">Локальный макет · 18 примеров</Badge> : page.total ? <p className="shrink-0 text-body font-medium text-[var(--text-muted)]">Опубликовано: {page.total}</p> : null}</header>
        {page.items.length ? <div className="mt-8 grid items-start gap-5 md:grid-cols-2 xl:grid-cols-3">{page.items.map((review) => <Card key={review.id} className="flex min-h-full flex-col rounded-lg border-[var(--border)] bg-[var(--surface-card)] p-5 shadow-none md:p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-[var(--text-primary)]">{review.publicName}</p><div className="mt-2 flex gap-1" aria-label={`Оценка ${review.rating} из 5`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`size-4 ${index < review.rating ? 'fill-[var(--accent)] text-[var(--accent)]' : 'text-[var(--border)]'}`} aria-hidden />)}</div></div><time dateTime={review.publishedAt} className="shrink-0 text-label text-[var(--text-muted)]">{review.dateLabel}</time></div>{review.text.length > 420 ? <details className="group mt-5"><summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden"><span className="block group-open:hidden"><span className="line-clamp-7 whitespace-pre-line text-body leading-step-copy text-[var(--text-secondary)]">{review.text}</span><span className="mt-3 block w-fit text-body font-semibold text-[var(--accent)] hover:text-[var(--accent-hover)]">Читать полностью</span></span><span className="hidden w-fit text-body font-semibold text-[var(--accent)] hover:text-[var(--accent-hover)] group-open:block">Свернуть</span></summary><span className="mt-4 hidden whitespace-pre-line text-body leading-step-copy text-[var(--text-secondary)] group-open:block">{review.text}</span></details> : <p className="mt-5 whitespace-pre-line text-body leading-step-copy text-[var(--text-secondary)]">{review.text}</p>}<div className="mt-6 border-t border-[var(--border-soft)] pt-5"><LinkRenderer href={`/sotrudniki/${review.employee.slug}`} className="group inline-flex items-center gap-3"><span className="relative h-12 w-14 shrink-0 overflow-hidden rounded-lg bg-[var(--background)]"><ImageRenderer src={review.employee.photoUrl || placeholderImage} alt={review.employee.photoUrl ? review.employee.fullName : ""} fill sizes="56px" className={review.employee.photoUrl ? "object-cover object-top" : "object-contain object-bottom"} /></span><span className="min-w-0"><span className="block text-body font-semibold text-[var(--text-primary)] transition group-hover:text-[var(--accent)]">{review.employee.fullName}</span><span className="mt-0.5 block text-label leading-step-body text-[var(--text-muted)]">{review.employee.position}</span></span></LinkRenderer></div></Card>)}</div> : <div className="mt-8 rounded-lg border border-dashed border-[var(--border)] bg-[var(--surface-card)] p-7 text-body text-[var(--text-secondary)]">Опубликованные отзывы о специалистах скоро появятся на этой странице.</div>}
        {page.pageCount > 1 ? <nav className="mt-9 flex items-center justify-center gap-4" aria-label="Пагинация отзывов">{page.previousHref ? <Button asChild variant="outline" size="sm"><LinkRenderer href={page.previousHref}>Назад</LinkRenderer></Button> : <span className="min-w-19.5" aria-hidden />}<span className="text-body text-[var(--text-muted)]">{page.page} из {page.pageCount}</span>{page.nextHref ? <Button asChild variant="outline" size="sm"><LinkRenderer href={page.nextHref}>Далее</LinkRenderer></Button> : <span className="min-w-19.5" aria-hidden />}</nav> : null}
      </div>
    </section>
  );
}
