import { BriefcaseBusiness, MessageSquareText, Star } from "lucide-react";
import type { EmployeeProfilePageDto } from "@starter/site-contracts";
import type { ReactNode } from "react";
import type { SiteLinkRenderer } from "../../lib/adapters";
import { Card } from "../../components/ui/card";

type Props = { page: EmployeeProfilePageDto; topBreadcrumbs: ReactNode; bottomBreadcrumbs: ReactNode; portrait: ReactNode; contactDetails: ReactNode; leadForm: ReactNode; reviewForm: ReactNode; listingCards: ReactNode[]; linkRenderer: SiteLinkRenderer };

export function EmployeeProfileView({ page, topBreadcrumbs, bottomBreadcrumbs, portrait, contactDetails, leadForm, reviewForm, listingCards, linkRenderer: LinkRenderer }: Props) {
  const { employee } = page;
  const pager = (items: EmployeeProfilePageDto["reviewPageLinks"], label: string) => items.length > 1 ? <nav className="mt-9 flex justify-center gap-2" aria-label={label}>{items.map((item) => <LinkRenderer key={item.href} href={item.href} ariaCurrent={item.current ? "page" : undefined} className={`flex size-10 items-center justify-center rounded-lg border text-body font-medium ${item.current ? "border-[var(--surface-dark)] bg-[var(--surface-dark)] text-white" : "border-[var(--border)] bg-[var(--surface-card)] text-[var(--text-secondary)]"}`}>{item.label}</LinkRenderer>)}</nav> : null;
  return (
    <main className="min-h-screen bg-[var(--surface-card)] text-[var(--text-primary)]">
      <section className="mx-auto max-w-site-frame px-5 pb-10 pt-8 md:px-8 md:pb-14 md:pt-12 lg:px-10">
        <div className="mb-6">{topBreadcrumbs}</div>
        <div className="grid gap-6 lg:grid-cols-[minmax(0,1.6fr)_minmax(330px,.8fr)] lg:items-stretch">
          <Card className="overflow-hidden rounded-lg border-[var(--border)] bg-[var(--surface-card)] p-0 shadow-none lg:h-full"><div className="grid md:grid-cols-[minmax(280px,.86fr)_minmax(0,1.14fr)]"><div className="relative min-h-90 bg-[var(--surface-card)] md:min-h-110">{portrait}</div><div className="flex flex-col p-6 md:p-7 lg:p-8"><p className="text-label font-medium uppercase tracking-caps text-[var(--accent)]">{employee.position}</p><h1 className="mt-3 text-heading-large font-semibold leading-card-title md:text-profile-title">{employee.fullName}</h1><div className="mt-5 flex flex-wrap gap-4 text-body text-[var(--text-secondary)]">{page.showsObjects ? <span className="inline-flex items-center gap-2"><BriefcaseBusiness className="size-4 text-[var(--accent)]" aria-hidden />{employee.objectCount} объектов</span> : null}{page.showsReviews ? <span className="inline-flex items-center gap-2">{employee.rating ? <Star className="size-4 fill-[var(--accent)] text-[var(--accent)]" aria-hidden /> : <MessageSquareText className="size-4 text-[var(--accent)]" aria-hidden />}{employee.rating ? `${employee.rating} · ${employee.reviewCount} отзывов` : "Пока без отзывов"}</span> : null}</div><p className="mt-6 text-body-compact leading-step-copy text-[var(--text-secondary)]">{employee.bio}</p><div className="mt-auto pt-6">{contactDetails}</div></div></div></Card>
          <aside id="svyazatsya" className="scroll-mt-32 lg:h-full">{leadForm}</aside>
        </div>
      </section>
      {page.showsReviews ? <section className="border-y border-[var(--border)] bg-[var(--surface-card)]"><div className="mx-auto max-w-site-frame px-5 py-12 md:px-8 md:py-16 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-label font-medium uppercase tracking-caps text-[var(--accent)]">Опыт клиентов</p><h2 className="mt-2 text-section-small font-semibold md:text-heading-large">Отзывы о специалисте</h2></div>{reviewForm}</div>{page.reviews.length ? <div className="mt-8 grid gap-4 md:grid-cols-2">{page.reviews.map((review) => <Card key={review.id} className="rounded-lg border-[var(--border)] bg-[var(--surface-card)] p-5 shadow-none md:p-6"><div className="flex items-center justify-between gap-4"><strong className="font-semibold">{review.publicName}</strong><time className="text-label text-[var(--text-muted)]">{review.dateLabel}</time></div><div className="mt-3 flex gap-1" aria-label={`Оценка ${review.rating} из 5`}>{Array.from({ length: 5 }, (_, index) => <Star key={index} className={`size-4 ${index < review.rating ? "fill-[var(--accent)] text-[var(--accent)]" : "text-[var(--border)]"}`} aria-hidden />)}</div><p className="mt-4 whitespace-pre-line text-body leading-step-copy text-[var(--text-secondary)]">{review.text}</p></Card>)}</div> : <div className="mt-8 rounded-lg border border-dashed border-[var(--border)] bg-[var(--surface-card)] p-7 text-body leading-step-copy text-[var(--text-secondary)]">У специалиста пока нет опубликованных отзывов. Вы можете поделиться реальным опытом работы.</div>}{pager(page.reviewPageLinks, "Пагинация отзывов")}</div></section> : null}
      {page.showsObjects ? <section className="mx-auto max-w-site-frame px-5 py-12 md:px-8 md:py-16 lg:px-10"><div><p className="text-label font-medium uppercase tracking-caps text-[var(--accent)]">Актуальная база</p><h2 className="mt-2 text-section-small font-semibold md:text-heading-large">Объекты специалиста</h2></div><div className="mt-7 flex flex-wrap gap-2">{page.categoryFilters.map((item) => <LinkRenderer key={item.href} href={item.href} ariaCurrent={item.active ? "page" : undefined} className={`rounded-lg border px-4 py-2.5 text-body font-medium transition ${item.active ? "border-[var(--surface-dark)] bg-[var(--surface-dark)] text-white" : "border-[var(--border)] bg-[var(--surface-card)] text-[var(--text-secondary)] hover:border-[var(--accent)] hover:text-[var(--accent)]"}`}>{item.label}</LinkRenderer>)}</div>{listingCards.length ? <div className="mt-8 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{listingCards}</div> : <div className="mt-8 rounded-lg border border-dashed border-[var(--border)] bg-[var(--surface-card)] p-7 text-body text-[var(--text-secondary)]">По выбранному фильтру активных объектов нет.</div>}{pager(page.listingPageLinks, "Пагинация объектов")}</section> : null}
      <section className="border-t border-[var(--border)] bg-[var(--surface-card)]"><div className="mx-auto max-w-site-frame px-5 pb-16 pt-10 md:px-8 md:pb-20 md:pt-12 lg:px-10">{bottomBreadcrumbs}</div></section>
    </main>
  );
}
