import { ArrowRight, BookOpen, Building2, Mail, MapPin, Phone, Quote, Star, UserRound } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import type { ReactNode } from 'react'

import type { PublicContacts, PublicEmployee, PublicOffice, PublicReview } from '@/payload/public/queries'

import { Breadcrumbs } from './Breadcrumbs'

const FRAME = 'mx-auto w-full max-w-site-frame px-5 lg:px-10 xl:px-12'

export function EmployeesPage({ employees }: { employees: PublicEmployee[] }) {
  return <DirectoryShell eyebrow="Команда" title="Специалисты Союза Застройщиков" description="Публичные профили сотрудников управляются в Payload и появляются здесь только после разрешения на публикацию."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{employees.length ? employees.map((employee) => <Link className="group overflow-hidden rounded-lg border border-[#E3E3E1] bg-white" href={`/sotrudniki/${employee.id}`} key={employee.id}><div className="relative aspect-[4/3] bg-[#F1F0EF]">{employee.photo ? <Image alt={employee.photo.alt} className="object-cover transition duration-500 group-hover:scale-[1.02]" fill sizes="(min-width:1024px) 33vw, 50vw" src={employee.photo.src} /> : <UserRound className="absolute left-1/2 top-1/2 size-14 -translate-x-1/2 -translate-y-1/2 text-[#B4B2B0]" />}</div><div className="p-5"><p className="text-xs font-semibold uppercase tracking-[.08em] text-[#8A1515]">{employee.position}</p><h2 className="mt-2 text-xl font-bold">{employee.name}</h2>{employee.bio ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-[#827F81]">{employee.bio}</p> : null}<span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold">Профиль <ArrowRight className="size-4" /></span></div></Link>) : <EmptyState icon={UserRound} title="Публичные профили пока не опубликованы" text="Команда появится после проверки данных и разрешения сотрудников на публикацию." />}</div></DirectoryShell>
}

export function EmployeeProfilePage({ employee }: { employee: PublicEmployee }) {
  return <main className="bg-[#FAFAFA] pb-16 lg:pb-24"><div className={`${FRAME} py-7 lg:py-10`}><Breadcrumbs items={[{ href: '/', label: 'Главная' }, { href: '/sotrudniki', label: 'Сотрудники' }, { label: employee.name }]} /><section className="mt-7 grid overflow-hidden rounded-lg border border-[#E3E3E1] bg-white lg:grid-cols-[minmax(320px,.8fr)_1.2fr]"><div className="relative min-h-[360px] bg-[#F1F0EF] lg:min-h-[590px]">{employee.photo ? <Image alt={employee.photo.alt} className="object-cover" fill priority sizes="(min-width:1024px) 45vw, 100vw" src={employee.photo.src} /> : <UserRound className="absolute left-1/2 top-1/2 size-20 -translate-x-1/2 -translate-y-1/2 text-[#B4B2B0]" />}</div><div className="flex flex-col justify-center p-7 lg:p-12"><p className="text-xs font-bold uppercase tracking-[.1em] text-[#8A1515]">{employee.position}</p><h1 className="mt-3 text-4xl font-extrabold leading-tight lg:text-5xl">{employee.name}</h1><p className="mt-6 whitespace-pre-line text-base leading-8 text-[#413F41]">{employee.bio || 'Информация о специалисте уточняется.'}</p><div className="mt-8 flex flex-wrap gap-3">{employee.phone ? <a className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-[#17161A] px-5 text-sm font-bold text-white" href={`tel:${employee.phone.replace(/[^+\d]/g, '')}`}><Phone className="size-4" />Позвонить</a> : null}{employee.email ? <a className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-[#E3E3E1] bg-white px-5 text-sm font-bold" href={`mailto:${employee.email}`}><Mail className="size-4" />Написать</a> : null}</div></div></section></div></main>
}

export function ReviewsDirectory({ reviews }: { reviews: PublicReview[] }) {
  return <section className="bg-white py-14 lg:py-20"><div className={FRAME}><p className="text-xs font-bold uppercase tracking-[.1em] text-[#8A1515]">Проверяемая обратная связь</p><h2 className="mt-3 text-3xl font-bold md:text-4xl">Отзывы клиентов</h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{reviews.length ? reviews.map((review) => <article className="grid gap-5 rounded-lg border border-[#E3E3E1] bg-[#FAFAFA] p-6" key={review.id}><div className="flex items-center justify-between"><Quote className="size-6 text-[#8A1515]" /><span className="flex gap-0.5" aria-label={`Оценка ${review.rating} из 5`}>{Array.from({ length: 5 }, (_, index) => <Star className={`size-3.5 ${index < review.rating ? 'fill-[#FF7A00] text-[#FF7A00]' : 'text-[#D0D0CD]'}`} key={index} />)}</span></div><p className="text-sm leading-7 text-[#413F41]">{review.text}</p><footer><strong className="block text-sm">{review.author}</strong>{review.employee ? <span className="mt-1 block text-xs text-[#827F81]">Специалист: {review.employee}</span> : null}<time className="mt-1 block text-xs text-[#827F81]">{new Intl.DateTimeFormat('ru-RU').format(new Date(review.date))}</time></footer></article>) : <EmptyState icon={Quote} title="Отзывы готовятся к публикации" text="Раздел остаётся пустым, пока модератор не подтвердит реальные отзывы в Payload." />}</div></div></section>
}

export function OfficesDirectory({ contacts, offices }: { contacts: PublicContacts; offices: PublicOffice[] }) {
  return <section className="bg-white py-14 lg:py-20" id="contact-details"><div className={FRAME}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[Phone, 'Телефон', contacts.phone], [Mail, 'Email', contacts.email], [MapPin, 'Адрес', contacts.address], [Building2, 'Режим работы', contacts.workingHours]].map(([Icon, label, value]) => { const ContactIcon = Icon as typeof Phone; return <article className="rounded-lg border border-[#E3E3E1] bg-[#FAFAFA] p-6" key={String(label)}><ContactIcon className="size-5 text-[#8A1515]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[.1em] text-[#827F81]">{String(label)}</p><strong className="mt-2 block leading-6">{String(value || 'Уточняется')}</strong></article> })}</div>{offices.length ? <div className="mt-8 grid gap-4 md:grid-cols-2">{offices.map((office) => <article className="overflow-hidden rounded-lg border border-[#E3E3E1]" key={office.id}>{office.photo ? <div className="relative aspect-[16/8]"><Image alt={office.photo.alt} className="object-cover" fill sizes="50vw" src={office.photo.src} /></div> : null}<div className="p-5"><h3 className="text-xl font-bold">{office.title}</h3><p className="mt-2 text-sm text-[#827F81]">{office.address}</p></div></article>)}</div> : null}</div></section>
}

export function JournalPage() {
  return <DirectoryShell eyebrow="Журнал" title="Практика покупки и строительства недвижимости" description="Материалы будут публиковаться после появления канонической коллекции статей в Payload. Вымышленные статьи не создаются."><div className="grid gap-4 rounded-lg border border-[#E3E3E1] bg-white p-8 text-center"><BookOpen className="mx-auto size-10 text-[#8A1515]" /><h2 className="text-2xl font-bold">Журнал готов к публикациям</h2><p className="mx-auto max-w-xl text-sm leading-6 text-[#827F81]">Сейчас в CMS нет коллекции статей. Поэтому маршрут и состояние перенесены, но контент не подменён демонстрационными материалами.</p></div></DirectoryShell>
}

export function HtmlSitemapPage() {
  const groups = [{ title: 'Недвижимость', links: [['Все объекты', '/nedvizhimost-rostov'], ['Новостройки', '/novostroyki-rostova'], ['Квартиры', '/kvartiry-rostova'], ['Дома', '/doma-rostov'], ['Коммерческая недвижимость', '/kommercheskaya-nedvizhimost']] }, { title: 'Сервисы', links: [['Ипотека', '/ipoteka'], ['Семейная ипотека', '/semeinaya-ipoteka-rostov'], ['Строительство домов', '/stroitelstvo-domov']] }, { title: 'Компания', links: [['О компании', '/about'], ['Сотрудники', '/sotrudniki'], ['Отзывы', '/reviews'], ['Контакты', '/contacts'], ['Вакансии', '/rabota-rieltorom-rostov'], ['Журнал', '/journal']] }]
  return <DirectoryShell eyebrow="Навигация" title="Карта сайта" description="Основные публичные разделы платформы."><div className="grid gap-4 md:grid-cols-3">{groups.map((group) => <section className="rounded-lg border border-[#E3E3E1] bg-white p-6" key={group.title}><h2 className="text-xl font-bold">{group.title}</h2><nav className="mt-5 grid gap-3">{group.links.map(([label, href]) => <Link className="text-sm text-[#413F41] hover:text-[#8A1515]" href={href} key={href}>{label}</Link>)}</nav></section>)}</div></DirectoryShell>
}

export function LegalPage() {
  return <DirectoryShell eyebrow="Правовая информация" title="Документы и правила использования сайта" description="Публичные правовые документы размещаются только после утверждения владельцем."><div className="grid gap-4 md:grid-cols-2"><LegalCard title="Политика обработки персональных данных">До утверждения юридического текста сайт не заявляет несуществующие условия обработки данных. Обращения направляются через опубликованные контакты.</LegalCard><LegalCard title="Пользовательское соглашение">Условия использования, ответственность сторон и порядок обращений требуют отдельного утверждённого документа.</LegalCard></div></DirectoryShell>
}

export function LeadgenPage({ kind }: { kind: 'apartments' | 'construction' | 'new-buildings' }) {
  const data = kind === 'construction' ? { eyebrow: 'Строительство дома', title: 'Проверьте участок, бюджет и этапы до договора', text: 'Получите маршрут проверки проекта без обещаний автоматического расчёта.', image: '/images/ui-construction.jpg', href: '/contacts?request=construction' } : kind === 'apartments' ? { eyebrow: 'Подбор квартиры', title: 'Сравните квартиры по бюджету, району и сроку', text: 'Каталог использует только опубликованные объекты Payload.', image: '/images/ui-home-hero.webp', href: '/kvartiry-rostova' } : { eyebrow: 'Новостройки Ростова', title: 'Выберите жилой комплекс по проверенным условиям', text: 'Показываем только опубликованные данные застройщиков.', image: '/images/ui-home-hero.webp', href: '/novostroyki-rostova' }
  return <main className="min-h-screen bg-[#17161A] text-white"><section className="relative flex min-h-screen items-end overflow-hidden"><Image alt="" className="object-cover opacity-50" fill priority sizes="100vw" src={data.image} /><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/50 to-black/15" /><div className="relative mx-auto w-full max-w-site-frame px-5 py-14 lg:px-10 lg:py-20"><p className="text-xs font-bold uppercase tracking-[.14em] text-white/55">{data.eyebrow}</p><h1 className="mt-4 max-w-4xl text-balance text-4xl font-extrabold leading-[.98] md:text-6xl">{data.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/70">{data.text}</p><Link className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#8A1515] px-6 font-bold" href={data.href}>Продолжить <ArrowRight className="size-4" /></Link><p className="mt-4 max-w-xl text-xs leading-5 text-white/45">Форма не имитирует отправку: обращение оформляется только через действующий контактный маршрут.</p></div></section></main>
}

function DirectoryShell({ children, description, eyebrow, title }: { children: ReactNode; description: string; eyebrow: string; title: string }) { return <main className="min-h-screen bg-[#FAFAFA] pb-16 lg:pb-24"><section className="bg-white py-8 lg:py-12"><div className={FRAME}><Breadcrumbs className="mb-7" items={[{ href: '/', label: 'Главная' }, { label: eyebrow }]} /><p className="text-xs font-bold uppercase tracking-[.12em] text-[#8A1515]">{eyebrow}</p><h1 className="mt-3 max-w-4xl text-balance text-4xl font-extrabold leading-tight md:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-[#827F81]">{description}</p></div></section><section className="pt-10 lg:pt-14"><div className={FRAME}>{children}</div></section></main> }
function EmptyState({ icon: Icon, text, title }: { icon: typeof UserRound; text: string; title: string }) { return <div className="col-span-full rounded-lg border border-dashed border-[#D0D0CD] bg-[#FAFAFA] p-10 text-center"><Icon className="mx-auto size-10 text-[#8A1515]" /><h2 className="mt-4 text-xl font-bold">{title}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#827F81]">{text}</p></div> }
function LegalCard({ children, title }: { children: ReactNode; title: string }) { return <article className="rounded-lg border border-[#E3E3E1] bg-white p-6"><h2 className="text-xl font-bold">{title}</h2><p className="mt-4 text-sm leading-7 text-[#413F41]">{children}</p><p className="mt-5 text-xs font-semibold text-[#8A1515]">Статус: требует утверждения</p></article> }
