import Link from 'next/link'
import type { AdminViewServerProps } from 'payload'

import { EmptyState, MetricCard, PaginationNav, TableCard, WorkspaceFrame } from '@/payload/admin/components/WorkspaceFrame'
import { ENTITY_ORIGIN_LABELS, PROPERTY_CATEGORY_LABELS, PROPERTY_STATUS_LABELS } from '@/payload/admin/lib/constants'
import { getPropertiesWorkspace } from '@/payload/admin/lib/workspaces'
import { getAdminViewContext } from '@/payload/admin/lib/context'

export async function PropertiesView(props: AdminViewServerProps) {
  const context = await getAdminViewContext(props)
  const data = await getPropertiesWorkspace(context, props.searchParams ?? {})

  return (
    <WorkspaceFrame actions={<Link className="sz-button" href="/admin/collections/properties/create">Новый объект</Link>} description="Каталог объектов недвижимости: ручные карточки, публикация, архив и медиа." title="Объекты">
      <div className="sz-metric-grid sz-metric-grid--four"><MetricCard label="Всего в базе" value={data.summary.total} /><MetricCard accent="emerald" label="На сайте" value={data.summary.published} /><MetricCard accent="blue" label="Ручные объекты" value={data.summary.manual} /><MetricCard accent="amber" label="Требуют внимания" value={data.summary.attention} /></div>
      <TableCard title="Состав базы"><div className="sz-pill-list">{data.categories.map((item) => <span className="sz-pill" key={item.label}>{item.label}: {item.value}</span>)}</div></TableCard>
      <form className="sz-filter-grid" method="get"><label><span>Поиск</span><input defaultValue={data.filters.search} name="search" placeholder="Название, адрес, код" type="text" /></label><label><span>Категория</span><select defaultValue={data.filters.category ?? ''} name="category"><option value="">Все</option>{Object.entries(PROPERTY_CATEGORY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Статус</span><select defaultValue={data.filters.status ?? ''} name="status"><option value="">Все</option>{Object.entries(PROPERTY_STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Ответственный</span><select defaultValue={data.filters.responsible ?? ''} name="responsible"><option value="">Все</option>{data.options.responsible.map((employee) => <option key={employee.id} value={employee.id}>{employee.fullName}</option>)}</select></label><label><span>Источник</span><select defaultValue={data.filters.origin ?? ''} name="origin"><option value="">Все</option>{Object.entries(ENTITY_ORIGIN_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label><span>Цена от</span><input defaultValue={data.filters.priceMin || ''} min={0} name="priceMin" type="number" /></label><label><span>Цена до</span><input defaultValue={data.filters.priceMax || ''} min={0} name="priceMax" type="number" /></label><label><span>Обновлено не раньше</span><input defaultValue={data.filters.updatedFrom ?? ''} name="updatedFrom" type="date" /></label><button className="sz-button" type="submit">Применить</button></form>
      <TableCard title="Список объектов">{data.properties.length === 0 ? <EmptyState>По текущим фильтрам объектов нет.</EmptyState> : <><table className="sz-table"><thead><tr><th>Название</th><th>Категория</th><th>Статус</th><th>Ответственный</th><th>Источник</th><th>Цена</th><th>Обновлено</th></tr></thead><tbody>{data.properties.map((property) => <tr key={property.id}><td><Link href={`/admin/collections/properties/${property.id}`}>{property.title}</Link></td><td>{PROPERTY_CATEGORY_LABELS[property.category]}</td><td>{PROPERTY_STATUS_LABELS[property.workflowStatus]}</td><td>{typeof property.responsibleEmployee === 'object' && property.responsibleEmployee ? property.responsibleEmployee.fullName : '—'}</td><td>{ENTITY_ORIGIN_LABELS[property.origin]}</td><td>{property.price ? new Intl.NumberFormat('ru-RU').format(property.price) : '—'}</td><td>{property.updatedFromSourceAt ? new Date(property.updatedFromSourceAt).toLocaleDateString('ru-RU') : new Date(property.updatedAt).toLocaleDateString('ru-RU')}</td></tr>)}</tbody></table><PaginationNav basePath="/admin/obekty" page={data.pagination.page} query={{ category: data.filters.category, origin: data.filters.origin, priceMax: data.filters.priceMax > 0 ? String(data.filters.priceMax) : undefined, priceMin: data.filters.priceMin > 0 ? String(data.filters.priceMin) : undefined, responsible: data.filters.responsible, search: data.filters.search, status: data.filters.status, updatedFrom: data.filters.updatedFrom }} totalPages={data.pagination.totalPages} /></>}</TableCard>
    </WorkspaceFrame>
  )
}
