"use client";

import { Checkbox } from "../../components/ui/checkbox";
import { Button } from "../../components/ui/button";
import { Table, TableBody, TableCaption, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { Building2, ChevronLeft, ChevronRight, ExternalLink, Trash2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { SessionCollectionItemDto } from "../../contracts/property";
import type { SiteImageRenderer, SiteLinkRenderer } from "../../lib/adapters";
import { formatArea as formatRealtyArea, formatRublePrice } from "../../lib/realty-format";

export function CompareTableView({ items, onRemove, linkRenderer: LinkRenderer, imageRenderer: ImageRenderer }: { items: SessionCollectionItemDto[]; onRemove: (id:string)=>void; linkRenderer: SiteLinkRenderer; imageRenderer: SiteImageRenderer }) {
  const scrollRef=useRef<HTMLDivElement>(null); const [onlyDifferences,setOnlyDifferences]=useState(false); const [left,setLeft]=useState(false); const [right,setRight]=useState(false); const [compact,setCompact]=useState(false);
  useEffect(()=>{const media=window.matchMedia("(max-width: 1023px)");const sync=()=>setCompact(media.matches);sync();media.addEventListener("change",sync);return()=>media.removeEventListener("change",sync);},[]);
  const labelWidth=compact?120:176; const columnWidth=compact?200:244;
  const rows=useMemo<CompareRow[]>(()=>[
    {label:"Стоимость",resolve:(item)=>formatPrice(item.price)}, {label:"Цена за м²",resolve:formatMeterPrice}, {label:"Адрес",resolve:(item)=>item.address}, {label:"Количество комнат",resolve:(item)=>item.rooms?String(item.rooms):"не указано"}, {label:"Общая площадь",resolve:(item)=>formatArea(item.area)}, {label:"Жилая",resolve:(item)=>formatArea(item.areaLiving)}, {label:"Кухня",resolve:(item)=>formatArea(item.areaKitchen)}, {label:"Этаж",resolve:formatFloor}, {label:"Ремонт",resolve:(item)=>item.renovation??"не указано"}, {label:"Материал постройки",resolve:(item)=>item.buildingType??"не указано"}, {label:"Год постройки",resolve:(item)=>item.builtYear?String(item.builtYear):"не указано"},
  ],[]);
  const visibleRows=onlyDifferences&&items.length>1?rows.filter((row)=>different(items,row.resolve)):rows;
  useEffect(()=>{const element=scrollRef.current;if(!element)return;const sync=()=>{const max=element.scrollWidth-element.clientWidth;setLeft(element.scrollLeft>8);setRight(element.scrollLeft<max-8);};sync();element.addEventListener("scroll",sync,{passive:true});window.addEventListener("resize",sync);return()=>{element.removeEventListener("scroll",sync);window.removeEventListener("resize",sync);};},[items.length,onlyDifferences,compact]);
  const scroll=(direction:"left"|"right")=>scrollRef.current?.scrollBy({left:direction==="right"?columnWidth+40:-(columnWidth+40),behavior:"smooth"});
  return <section className="mt-5 overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--surface-card)] shadow-[var(--compare-table-shadow-panel)] lg:mt-6">
    <header className="grid gap-4 border-b border-[var(--border)] bg-[var(--surface-card-soft)] px-4 py-4 md:grid-cols-[minmax(0,1fr)_auto] md:items-center md:px-5"><div><p className="text-body font-extrabold leading-step-body text-[var(--text-primary)]">{compareLabel(items)}</p><p className="mt-1 text-label font-medium leading-step-body text-[var(--text-muted)]">{compact?"Листайте объекты вправо. Слева закреплены названия параметров.":"Сравнивайте фото, цену и ключевые параметры. Доска рассчитана на комфортную работу с подборкой до 12 объектов."}</p></div><label className="inline-flex min-h-10 items-start gap-2 text-label font-semibold leading-step-body text-[var(--text-secondary)] md:items-center"><Checkbox checked={onlyDifferences} onCheckedChange={(checked)=>setOnlyDifferences(checked === true)} className="mt-1 md:mt-0"/><span>Показывать только отличия<span className="block font-medium text-[var(--text-muted)]">Скроем совпадающие строки</span></span></label></header>
    <div className="relative">{left?<Button variant="plain" type="button" onClick={()=>scroll("left")} className="absolute z-30 hidden size-11 items-center justify-center rounded-lg border border-[var(--border)] bg-[var(--surface-card)] text-[var(--text-primary)] shadow-[var(--compare-table-shadow-control)] transition hover:border-[var(--accent)] hover:text-[var(--accent)] lg:flex" style={{left:labelWidth+12,top:118}} aria-label="Прокрутить сравнение влево"><ChevronLeft className="" aria-hidden/></Button>:null}{right?<Button variant="plain" type="button" onClick={()=>scroll("right")} className="absolute right-4 top-[118px] z-30 hidden size-11 items-center justify-center rounded-lg border border-[var(--border)] bg-[var(--surface-card)] text-[var(--text-primary)] shadow-[var(--compare-table-shadow-control)] transition hover:border-[var(--accent)] hover:text-[var(--accent)] lg:flex" aria-label="Прокрутить сравнение вправо"><ChevronRight className="" aria-hidden/></Button>:null}
      <div ref={scrollRef} className="overflow-x-auto overscroll-x-contain [-webkit-overflow-scrolling:touch]">
        <Table className="w-max table-fixed">
          <TableCaption>Сравнение выбранных объектов недвижимости</TableCaption>
          <colgroup><col style={{ width: labelWidth }} />{items.map((item) => <col key={item.id} style={{ width: columnWidth }} />)}</colgroup>
          <TableHeader><TableRow className="border-[var(--border)]"><TableHead scope="col" className="sticky left-0 z-20 bg-[var(--surface-card)] px-3 py-4 text-body font-extrabold text-[var(--text-secondary)] shadow-[var(--compare-table-shadow-frozen-column)] md:px-5">Объекты<span className="mt-1 block text-label font-medium text-[var(--text-muted)]">Фото и стоимость</span></TableHead>{items.map((item)=><TableHead scope="col" key={item.id}><ObjectCard item={item} compact={compact} onRemove={()=>onRemove(item.id)} linkRenderer={LinkRenderer} imageRenderer={ImageRenderer}/></TableHead>)}</TableRow></TableHeader>
          <TableBody>{visibleRows.length?visibleRows.map((row)=><TableRow key={row.label}><TableHead scope="row" className="sticky left-0 z-20 bg-[var(--surface-card)] px-3 py-3 text-body font-extrabold leading-step-body text-[var(--text-secondary)] shadow-[var(--compare-table-shadow-frozen-column)] md:px-5">{row.label}</TableHead>{items.map((item)=><TableCell key={`${item.id}-${row.label}`} className="px-3 py-3 text-body font-medium leading-step-body text-[var(--text-primary)] md:px-4">{row.resolve(item)}</TableCell>)}</TableRow>):<TableRow><TableHead scope="row" className="sticky left-0 z-20 bg-[var(--surface-card)] px-3 py-4 text-body font-extrabold text-[var(--text-secondary)] shadow-[var(--compare-table-shadow-frozen-column)] md:px-5">Отличия</TableHead><TableCell className="px-3 py-4 text-body font-medium text-[var(--text-muted)] md:px-4" colSpan={Math.max(1, items.length)}>По базовым параметрам объекты совпадают.</TableCell></TableRow>}</TableBody>
        </Table>
      </div>
    </div>
  </section>;
}

function ObjectCard({item,onRemove,compact,linkRenderer:LinkRenderer,imageRenderer:ImageRenderer}:{item:SessionCollectionItemDto;onRemove:()=>void;compact:boolean;linkRenderer:SiteLinkRenderer;imageRenderer:SiteImageRenderer}){return <article className={`relative ${compact?"px-2.5 py-3":"px-3 py-4"}`}><Button variant="plain" type="button" onClick={onRemove} className="absolute right-3 top-5 z-10 inline-flex items-center justify-center rounded-lg bg-[var(--surface-dark)]/72 text-white backdrop-blur-sm transition hover:bg-[var(--accent)] md:right-5 md:top-6" aria-label="Убрать из сравнения"><Trash2 className="" aria-hidden/></Button><LinkRenderer href={item.path} className="group block"><div className="relative aspect-[4/3] overflow-hidden rounded-lg bg-[var(--surface-muted)]">{item.image?<ImageRenderer src={item.image} alt={item.title} fill unoptimized={item.image.startsWith("http")} sizes="244px" className="object-cover transition duration-500 group-hover:scale-[1.03]"/>:<span className="grid h-full place-items-center text-[var(--text-muted)]"><Building2 className="size-8" aria-hidden/></span>}</div><p className="mt-3 text-body-emphasis font-extrabold leading-flat tabular-nums text-[var(--text-primary)]">{formatPrice(item.price)}</p><p className="mt-1 text-label font-semibold leading-step-body text-[var(--text-muted)]">{formatMeterPrice(item)}</p><h2 className="mt-2 line-clamp-2 text-body font-extrabold leading-step-body text-[var(--text-primary)] transition group-hover:text-[var(--accent)]">{item.title}</h2><span className="mt-3 inline-flex min-h-9 items-center gap-2 rounded-lg border border-[var(--border)] px-3 text-label font-bold text-[var(--text-secondary)] transition group-hover:border-[var(--accent)] group-hover:text-[var(--accent)]">Открыть объект<ExternalLink className="size-3.5" aria-hidden/></span></LinkRenderer></article>;}
type CompareRow={label:string;resolve:(item:SessionCollectionItemDto)=>string};
const formatPrice = formatRublePrice;
function formatArea(value?:number|null){return formatRealtyArea(value,"не указано");}
function formatFloor(item:SessionCollectionItemDto){return item.floor?`${item.floor} из ${item.floorsTotal??"-"}`:"не указано";}
function formatMeterPrice(item:SessionCollectionItemDto){return item.price&&item.area?`${formatRublePrice(Math.round(item.price/item.area))}/м²`:"не указано";}
function different(items:SessionCollectionItemDto[],resolve:(item:SessionCollectionItemDto)=>string){return new Set(items.map((item)=>resolve(item).trim().toLowerCase())).size>1;}
function compareLabel(items:SessionCollectionItemDto[]){const keys=new Set(items.map((item)=>item.categoryKey));if(keys.size!==1)return `Объекты ${items.length}`;const key=items[0]?.categoryKey;const label=key==="flat"||key==="room"?"Квартиры":key==="house"?"Дома":key==="land"?"Участки":key==="commercial"?"Коммерция":key==="construction"?"Строительство":key==="new_building"?"Новостройки":"Объекты";return `${label} ${items.length}`;}
