/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    leads: Lead;
    'lead-notes': LeadNote;
    properties: Property;
    'residential-complexes': ResidentialComplex;
    employees: Employee;
    reviews: Review;
    offices: Office;
    'analytics-events': AnalyticsEvent;
    'anti-spam-events': AntiSpamEvent;
    'import-sources': ImportSource;
    'import-runs': ImportRun;
    'import-errors': ImportError;
    'admin-activities': AdminActivity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    leads: {
      notes: 'lead-notes';
      antiSpamAttempts: 'anti-spam-events';
      activity: 'admin-activities';
    };
    properties: {
      activity: 'admin-activities';
    };
    'residential-complexes': {
      activity: 'admin-activities';
    };
    employees: {
      properties: 'properties';
      reviews: 'reviews';
      activity: 'admin-activities';
    };
    reviews: {
      activity: 'admin-activities';
    };
    offices: {
      activity: 'admin-activities';
    };
    'import-runs': {
      errors: 'import-errors';
      activity: 'admin-activities';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-notes': LeadNotesSelect<false> | LeadNotesSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'residential-complexes': ResidentialComplexesSelect<false> | ResidentialComplexesSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>;
    'anti-spam-events': AntiSpamEventsSelect<false> | AntiSpamEventsSelect<true>;
    'import-sources': ImportSourcesSelect<false> | ImportSourcesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'import-errors': ImportErrorsSelect<false> | ImportErrorsSelect<true>;
    'admin-activities': AdminActivitiesSelect<false> | AdminActivitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'SUPER_ADMIN' | 'DIRECTOR' | 'CONTENT_MANAGER';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  isPublic?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  phone: string;
  email?: string | null;
  status:
    | 'new'
    | 'in_work'
    | 'deferred'
    | 'interest_confirmed'
    | 'selecting_options'
    | 'deposit_booking'
    | 'successful'
    | 'unsuccessful'
    | 'spam_duplicate';
  responsibleEmployee?: (number | null) | Employee;
  direction?: ('new_building' | 'construction' | 'flat' | 'house' | 'land' | 'commercial' | 'other') | null;
  formType?: string | null;
  source?: string | null;
  sourcePage?: string | null;
  visitorKeyHash?: string | null;
  interestType?: string | null;
  budget?: number | null;
  preferredDistrict?: string | null;
  desiredRooms?: number | null;
  paymentMethod?: string | null;
  purchaseTimeline?: string | null;
  nextContactAt?: string | null;
  message?: string | null;
  normalizedPhone?: string | null;
  duplicateCount?: number | null;
  lastDuplicateAt?: string | null;
  notes?: {
    docs?: (number | LeadNote)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  antiSpamAttempts?: {
    docs?: (number | AntiSpamEvent)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: number;
  fullName: string;
  publicName?: string | null;
  origin: 'MANUAL' | 'XML';
  status: 'active' | 'inactive';
  isPublic?: boolean | null;
  teamSection: 'sales' | 'support' | 'office' | 'management' | 'other';
  position?: string | null;
  phone?: string | null;
  email?: string | null;
  sortOrder?: number | null;
  photo?: (number | null) | Media;
  publicBio?: string | null;
  properties?: {
    docs?: (number | Property)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  reviews?: {
    docs?: (number | Review)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  title: string;
  objectCode?: string | null;
  externalId?: string | null;
  origin: 'MANUAL' | 'XML';
  workflowStatus: 'draft' | 'active' | 'archived' | 'hidden';
  isPublished?: boolean | null;
  category: 'flat' | 'room' | 'house' | 'land' | 'commercial';
  responsibleEmployee?: (number | null) | Employee;
  feedSource?: (number | null) | ImportSource;
  price?: number | null;
  dealType?: ('sale' | 'rent') | null;
  commercialType?: ('office' | 'retail' | 'warehouse' | 'business' | 'free_purpose') | null;
  totalArea?: number | null;
  livingArea?: number | null;
  kitchenArea?: number | null;
  floor?: number | null;
  floorsTotal?: number | null;
  buildYear?: number | null;
  buildingMaterial?: string | null;
  repair?: string | null;
  pricePerSquareMeter?: number | null;
  isStudio?: boolean | null;
  isExclusive?: boolean | null;
  city?: string | null;
  district?: string | null;
  addressLine?: string | null;
  coordinates?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  rooms?: number | null;
  updatedFromSourceAt?: string | null;
  publishedAt?: string | null;
  publicSlug?: string | null;
  description?: string | null;
  videoUrl?: string | null;
  gallery?:
    | {
        file: number | Media;
        kind: 'photo' | 'floor_plan';
        isMain?: boolean | null;
        id?: string | null;
      }[]
    | null;
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-sources".
 */
export interface ImportSource {
  id: number;
  title: string;
  endpointHint?: string | null;
  isActive?: boolean | null;
  adapterConfigured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-activities".
 */
export interface AdminActivity {
  id: number;
  event:
    | 'LEAD_CREATED'
    | 'LEAD_STAGE_CHANGED'
    | 'LEAD_NOTE_ADDED'
    | 'PROPERTY_CREATED'
    | 'PROPERTY_UPDATED'
    | 'PROPERTY_PUBLISHED'
    | 'PROPERTY_ARCHIVED'
    | 'PROPERTY_MEDIA_UPDATED'
    | 'COMPLEX_CREATED'
    | 'COMPLEX_UPDATED'
    | 'COMPLEX_PUBLISHED'
    | 'EMPLOYEE_UPDATED'
    | 'OFFICE_UPDATED'
    | 'REVIEW_PUBLISHED'
    | 'REVIEW_RETURNED_TO_MODERATION'
    | 'REVIEW_REJECTED'
    | 'CONTACTS_UPDATED'
    | 'IMPORT_FINISHED';
  label: string;
  details?: string | null;
  triggeredBy: string;
  lead?: (number | null) | Lead;
  property?: (number | null) | Property;
  residentialComplex?: (number | null) | ResidentialComplex;
  employee?: (number | null) | Employee;
  review?: (number | null) | Review;
  office?: (number | null) | Office;
  importRun?: (number | null) | ImportRun;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes".
 */
export interface ResidentialComplex {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'hidden';
  isFeatured?: boolean | null;
  sortOrder?: number | null;
  shortDescription?: string | null;
  description?: string | null;
  developer?: string | null;
  completionLabel?: string | null;
  district?: string | null;
  address?: string | null;
  priceFrom?: number | null;
  areaMin?: number | null;
  areaMax?: number | null;
  roomTypes?: ('studio' | '1' | '2' | '3' | '4')[] | null;
  cover?: (number | null) | Media;
  externalCoverUrl?: string | null;
  videoUrl?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        externalUrl?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  advantages?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  purchaseTerms?:
    | {
        title: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  location?: {
    latitude?: number | null;
    longitude?: number | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  authorName: string;
  publicName?: string | null;
  employee: number | Employee;
  rating: number;
  status: 'pending' | 'published' | 'rejected';
  reviewDate: string;
  text: string;
  publishedText?: string | null;
  authorPhone?: string | null;
  consentGiven?: boolean | null;
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: number;
  title: string;
  address: string;
  photo?: (number | null) | Media;
  sortOrder: number;
  isPublished?: boolean | null;
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  source?: (number | null) | ImportSource;
  status: 'running' | 'success' | 'partial_success' | 'failed' | 'cancelled';
  startedAt: string;
  finishedAt?: string | null;
  receivedCount?: number | null;
  createdCount?: number | null;
  updatedCount?: number | null;
  skippedCount?: number | null;
  failedCount?: number | null;
  unchangedCount?: number | null;
  summary?: string | null;
  diagnostics?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  errors?: {
    docs?: (number | ImportError)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  activity?: {
    docs?: (number | AdminActivity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-errors".
 */
export interface ImportError {
  id: number;
  run: number | ImportRun;
  externalId?: string | null;
  code?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-notes".
 */
export interface LeadNote {
  id: number;
  lead: number | Lead;
  body: string;
  authorName?: string | null;
  notedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anti-spam-events".
 */
export interface AntiSpamEvent {
  id: number;
  verdict: 'accepted' | 'duplicate_suppressed' | 'rate_limited' | 'honeypot' | 'blocked_too_fast' | 'suspicious_burst';
  reason?: string | null;
  sourcePage?: string | null;
  formType?: string | null;
  lead?: (number | null) | Lead;
  clientIpHash?: string | null;
  visitorKeyHash?: string | null;
  requestFingerprintHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: number;
  eventType: 'visit' | 'lead_conversion';
  occurredAt: string;
  section?: string | null;
  page: string;
  utmSource?: string | null;
  device: 'desktop' | 'mobile' | 'tablet' | 'unknown';
  visitorKeyHash: string;
  sessionKeyHash?: string | null;
  lead?: (number | null) | Lead;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-notes';
        value: number | LeadNote;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'residential-complexes';
        value: number | ResidentialComplex;
      } | null)
    | ({
        relationTo: 'employees';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'offices';
        value: number | Office;
      } | null)
    | ({
        relationTo: 'analytics-events';
        value: number | AnalyticsEvent;
      } | null)
    | ({
        relationTo: 'anti-spam-events';
        value: number | AntiSpamEvent;
      } | null)
    | ({
        relationTo: 'import-sources';
        value: number | ImportSource;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null)
    | ({
        relationTo: 'import-errors';
        value: number | ImportError;
      } | null)
    | ({
        relationTo: 'admin-activities';
        value: number | AdminActivity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isPublic?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  status?: T;
  responsibleEmployee?: T;
  direction?: T;
  formType?: T;
  source?: T;
  sourcePage?: T;
  visitorKeyHash?: T;
  interestType?: T;
  budget?: T;
  preferredDistrict?: T;
  desiredRooms?: T;
  paymentMethod?: T;
  purchaseTimeline?: T;
  nextContactAt?: T;
  message?: T;
  normalizedPhone?: T;
  duplicateCount?: T;
  lastDuplicateAt?: T;
  notes?: T;
  antiSpamAttempts?: T;
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-notes_select".
 */
export interface LeadNotesSelect<T extends boolean = true> {
  lead?: T;
  body?: T;
  authorName?: T;
  notedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  title?: T;
  objectCode?: T;
  externalId?: T;
  origin?: T;
  workflowStatus?: T;
  isPublished?: T;
  category?: T;
  responsibleEmployee?: T;
  feedSource?: T;
  price?: T;
  dealType?: T;
  commercialType?: T;
  totalArea?: T;
  livingArea?: T;
  kitchenArea?: T;
  floor?: T;
  floorsTotal?: T;
  buildYear?: T;
  buildingMaterial?: T;
  repair?: T;
  pricePerSquareMeter?: T;
  isStudio?: T;
  isExclusive?: T;
  city?: T;
  district?: T;
  addressLine?: T;
  coordinates?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  rooms?: T;
  updatedFromSourceAt?: T;
  publishedAt?: T;
  publicSlug?: T;
  description?: T;
  videoUrl?: T;
  gallery?:
    | T
    | {
        file?: T;
        kind?: T;
        isMain?: T;
        id?: T;
      };
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes_select".
 */
export interface ResidentialComplexesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  isFeatured?: T;
  sortOrder?: T;
  shortDescription?: T;
  description?: T;
  developer?: T;
  completionLabel?: T;
  district?: T;
  address?: T;
  priceFrom?: T;
  areaMin?: T;
  areaMax?: T;
  roomTypes?: T;
  cover?: T;
  externalCoverUrl?: T;
  videoUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        externalUrl?: T;
        alt?: T;
        id?: T;
      };
  advantages?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  purchaseTerms?:
    | T
    | {
        title?: T;
        value?: T;
        id?: T;
      };
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  fullName?: T;
  publicName?: T;
  origin?: T;
  status?: T;
  isPublic?: T;
  teamSection?: T;
  position?: T;
  phone?: T;
  email?: T;
  sortOrder?: T;
  photo?: T;
  publicBio?: T;
  properties?: T;
  reviews?: T;
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  authorName?: T;
  publicName?: T;
  employee?: T;
  rating?: T;
  status?: T;
  reviewDate?: T;
  text?: T;
  publishedText?: T;
  authorPhone?: T;
  consentGiven?: T;
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  title?: T;
  address?: T;
  photo?: T;
  sortOrder?: T;
  isPublished?: T;
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  eventType?: T;
  occurredAt?: T;
  section?: T;
  page?: T;
  utmSource?: T;
  device?: T;
  visitorKeyHash?: T;
  sessionKeyHash?: T;
  lead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anti-spam-events_select".
 */
export interface AntiSpamEventsSelect<T extends boolean = true> {
  verdict?: T;
  reason?: T;
  sourcePage?: T;
  formType?: T;
  lead?: T;
  clientIpHash?: T;
  visitorKeyHash?: T;
  requestFingerprintHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-sources_select".
 */
export interface ImportSourcesSelect<T extends boolean = true> {
  title?: T;
  endpointHint?: T;
  isActive?: T;
  adapterConfigured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  source?: T;
  status?: T;
  startedAt?: T;
  finishedAt?: T;
  receivedCount?: T;
  createdCount?: T;
  updatedCount?: T;
  skippedCount?: T;
  failedCount?: T;
  unchangedCount?: T;
  summary?: T;
  diagnostics?: T;
  errors?: T;
  activity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-errors_select".
 */
export interface ImportErrorsSelect<T extends boolean = true> {
  run?: T;
  externalId?: T;
  code?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-activities_select".
 */
export interface AdminActivitiesSelect<T extends boolean = true> {
  event?: T;
  label?: T;
  details?: T;
  triggeredBy?: T;
  lead?: T;
  property?: T;
  residentialComplex?: T;
  employee?: T;
  review?: T;
  office?: T;
  importRun?: T;
  before?: T;
  after?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  brandName: string;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  telegramUrl?: string | null;
  vkUrl?: string | null;
  projectName?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSEO?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  brandName?: T;
  phone?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  telegramUrl?: T;
  vkUrl?: T;
  projectName?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}