/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    leads: Lead;
    'lead-deliveries': LeadDelivery;
    properties: Property;
    'residential-complexes': ResidentialComplex;
    buildings: Building;
    developers: Developer;
    agents: Agent;
    'feed-sources': FeedSource;
    'import-runs': ImportRun;
    'import-issues': ImportIssue;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-deliveries': LeadDeliveriesSelect<false> | LeadDeliveriesSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    'residential-complexes': ResidentialComplexesSelect<false> | ResidentialComplexesSelect<true>;
    buildings: BuildingsSelect<false> | BuildingsSelect<true>;
    developers: DevelopersSelect<false> | DevelopersSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'feed-sources': FeedSourcesSelect<false> | FeedSourcesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    'import-issues': ImportIssuesSelect<false> | ImportIssuesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      applyLeadRetention: TaskApplyLeadRetention;
      deliverLead: TaskDeliverLead;
      importFeed: TaskImportFeed;
      recoverLeadDeliveries: TaskRecoverLeadDeliveries;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'owner' | 'editor';
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  isPublic?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (string | null) | Media;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  name?: string | null;
  phone: string;
  normalizedPhone: string;
  email?: string | null;
  message?: string | null;
  status: 'new' | 'in_progress' | 'closed' | 'rejected';
  property?: (string | null) | Property;
  complex?: (string | null) | ResidentialComplex;
  agent?: (string | null) | Agent;
  sourcePage?: string | null;
  consentVersion: string;
  consentedAt: string;
  idempotencyKey: string;
  personalDataPurgedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: string;
  feedSource?: (string | null) | FeedSource;
  externalId?: string | null;
  origin: 'manual' | 'feed';
  importHash?: string | null;
  firstSeenAt?: string | null;
  lastSeenAt?: string | null;
  lastImportRun?: (string | null) | ImportRun;
  manualFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  needsReview?: boolean | null;
  duplicateOf?: (string | null) | Property;
  duplicateCandidates?: (string | Property)[] | null;
  status: 'active' | 'reserved' | 'sold' | 'removed';
  isPublished?: boolean | null;
  publishedAt?: string | null;
  slug: string;
  isFeatured?: boolean | null;
  market: 'secondary' | 'newbuild';
  dealType: 'sale' | 'rent';
  category: 'apartment' | 'house' | 'townhouse' | 'land' | 'commercial' | 'parking';
  dealStatus?: ('available' | 'reserved' | 'sold') | null;
  isApartments?: boolean | null;
  priceMinorUnits: number;
  currency: 'RUB';
  pricePerMeterMinorUnits?: number | null;
  isPriceNegotiable?: boolean | null;
  mortgageAvailable?: boolean | null;
  totalAreaCm2: number;
  livingAreaCm2?: number | null;
  kitchenAreaCm2?: number | null;
  rooms?: number | null;
  floor?: number | null;
  floorsTotal?: number | null;
  ceilingHeightCm?: number | null;
  layoutImage?: (string | null) | Media;
  complex?: (string | null) | ResidentialComplex;
  building?: (string | null) | Building;
  buildingType?: string | null;
  builtYear?: number | null;
  readyQuarter?: string | null;
  buildingState?: string | null;
  developerName?: string | null;
  region?: string | null;
  district?: string | null;
  localityName?: string | null;
  subLocalityName?: string | null;
  street?: string | null;
  houseNumber?: string | null;
  addressPublic?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  geoPrecision?: ('exact' | 'house' | 'street' | 'locality' | 'unknown') | null;
  apartmentNumber?: string | null;
  cadastralNumber?: string | null;
  internalComment?: string | null;
  ownerContact?: string | null;
  title: string;
  description?: string | null;
  photos?:
    | {
        media?: (string | null) | Media;
        externalUrl?: string | null;
        alt?: string | null;
        isMain?: boolean | null;
        id?: string | null;
      }[]
    | null;
  videoUrl?: string | null;
  agent?: (string | null) | Agent;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources".
 */
export interface FeedSource {
  id: string;
  code: string;
  title: string;
  market: 'secondary' | 'newbuild';
  parser: 'yrl-secondary' | 'yrl-newbuild';
  /**
   * Имя переменной окружения; URL в БД не хранится.
   */
  feedUrlRef: string;
  /**
   * Имя переменной окружения; секрет в БД не хранится.
   */
  credentialRef?: string | null;
  isEnabled?: boolean | null;
  priority: number;
  /**
   * Явный владелец импортируемого поля: ключ вида complex.name или building.address, значение — code источника.
   */
  fieldOwnership?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  minOffersThresholdPercent: number;
  maxOffersLimit: number;
  schedule?: string | null;
  lastSuccessfulRunAt?: string | null;
  lastOfferCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: string;
  correlationId: string;
  source: string | FeedSource;
  mode: 'delta' | 'full_snapshot';
  status: 'running' | 'success' | 'suspicious' | 'partial_success' | 'failed' | 'cancelled';
  startedAt: string;
  finishedAt?: string | null;
  total?: number | null;
  created?: number | null;
  updated?: number | null;
  unchanged?: number | null;
  skipped?: number | null;
  failed?: number | null;
  deactivated?: number | null;
  durationMs?: number | null;
  summary?: string | null;
  streamCompleted?: boolean | null;
  addressFormat?: ('structured' | 'freeform') | null;
  deactivationAllowed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes".
 */
export interface ResidentialComplex {
  id: string;
  name: string;
  slug: string;
  developer?: (string | null) | Developer;
  responsibleAgent?: (string | null) | Agent;
  yandexBuildingId?: string | null;
  importOwnership?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  region?: string | null;
  district?: string | null;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  description?: string | null;
  photos?:
    | {
        media?: (string | null) | Media;
        externalUrl?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  readiness?: ('planned' | 'construction' | 'commissioned') | null;
  propertyCount?: number | null;
  availablePropertyCount?: number | null;
  status: 'draft' | 'published' | 'hidden';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers".
 */
export interface Developer {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  logo?: (string | null) | Media;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: string;
  name: string;
  slug: string;
  origin: 'manual' | 'feed';
  feedSource?: (string | null) | FeedSource;
  externalId?: string | null;
  normalizedPhone?: string | null;
  phone?: string | null;
  email?: string | null;
  position?: string | null;
  bio?: string | null;
  photo?: (string | null) | Media;
  status: 'active' | 'inactive';
  isPublished?: boolean | null;
  importHash?: string | null;
  lastSeenAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    canonical?: string | null;
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings".
 */
export interface Building {
  id: string;
  complex: string | ResidentialComplex;
  name: string;
  yandexHouseId: string;
  importOwnership?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  section?: string | null;
  phase?: string | null;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  floors?: number | null;
  readiness?: ('planned' | 'construction' | 'commissioned') | null;
  handoverAt?: string | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-deliveries".
 */
export interface LeadDelivery {
  id: string;
  lead: string | Lead;
  channel: string;
  routeReason: 'property-agent' | 'complex-agent' | 'type-mapping' | 'fallback';
  recipientAgent?: (string | null) | Agent;
  status: 'pending' | 'processing' | 'delivered' | 'failed' | 'dead';
  attempts: number;
  nextAttemptAt?: string | null;
  lockedAt?: string | null;
  lastAttemptAt?: string | null;
  deliveredAt?: string | null;
  idempotencyKey: string;
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-issues".
 */
export interface ImportIssue {
  id: string;
  run: string | ImportRun;
  severity: 'warning' | 'error' | 'critical';
  externalId?: string | null;
  code: string;
  message: string;
  recordIndex?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'properties';
          value: string | Property;
        } | null)
      | ({
          relationTo: 'residential-complexes';
          value: string | ResidentialComplex;
        } | null)
      | ({
          relationTo: 'agents';
          value: string | Agent;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  type: '301' | '302' | '307' | '308';
  isEnabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'applyLeadRetention' | 'deliverLead' | 'importFeed' | 'recoverLeadDeliveries';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'applyLeadRetention' | 'deliverLead' | 'importFeed' | 'recoverLeadDeliveries') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'lead-deliveries';
        value: string | LeadDelivery;
      } | null)
    | ({
        relationTo: 'properties';
        value: string | Property;
      } | null)
    | ({
        relationTo: 'residential-complexes';
        value: string | ResidentialComplex;
      } | null)
    | ({
        relationTo: 'buildings';
        value: string | Building;
      } | null)
    | ({
        relationTo: 'developers';
        value: string | Developer;
      } | null)
    | ({
        relationTo: 'agents';
        value: string | Agent;
      } | null)
    | ({
        relationTo: 'feed-sources';
        value: string | FeedSource;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: string | ImportRun;
      } | null)
    | ({
        relationTo: 'import-issues';
        value: string | ImportIssue;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  isPublic?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  cover?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  normalizedPhone?: T;
  email?: T;
  message?: T;
  status?: T;
  property?: T;
  complex?: T;
  agent?: T;
  sourcePage?: T;
  consentVersion?: T;
  consentedAt?: T;
  idempotencyKey?: T;
  personalDataPurgedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-deliveries_select".
 */
export interface LeadDeliveriesSelect<T extends boolean = true> {
  lead?: T;
  channel?: T;
  routeReason?: T;
  recipientAgent?: T;
  status?: T;
  attempts?: T;
  nextAttemptAt?: T;
  lockedAt?: T;
  lastAttemptAt?: T;
  deliveredAt?: T;
  idempotencyKey?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  feedSource?: T;
  externalId?: T;
  origin?: T;
  importHash?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  lastImportRun?: T;
  manualFields?: T;
  needsReview?: T;
  duplicateOf?: T;
  duplicateCandidates?: T;
  status?: T;
  isPublished?: T;
  publishedAt?: T;
  slug?: T;
  isFeatured?: T;
  market?: T;
  dealType?: T;
  category?: T;
  dealStatus?: T;
  isApartments?: T;
  priceMinorUnits?: T;
  currency?: T;
  pricePerMeterMinorUnits?: T;
  isPriceNegotiable?: T;
  mortgageAvailable?: T;
  totalAreaCm2?: T;
  livingAreaCm2?: T;
  kitchenAreaCm2?: T;
  rooms?: T;
  floor?: T;
  floorsTotal?: T;
  ceilingHeightCm?: T;
  layoutImage?: T;
  complex?: T;
  building?: T;
  buildingType?: T;
  builtYear?: T;
  readyQuarter?: T;
  buildingState?: T;
  developerName?: T;
  region?: T;
  district?: T;
  localityName?: T;
  subLocalityName?: T;
  street?: T;
  houseNumber?: T;
  addressPublic?: T;
  latitude?: T;
  longitude?: T;
  geoPrecision?: T;
  apartmentNumber?: T;
  cadastralNumber?: T;
  internalComment?: T;
  ownerContact?: T;
  title?: T;
  description?: T;
  photos?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
        isMain?: T;
        id?: T;
      };
  videoUrl?: T;
  agent?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes_select".
 */
export interface ResidentialComplexesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  developer?: T;
  responsibleAgent?: T;
  yandexBuildingId?: T;
  importOwnership?: T;
  region?: T;
  district?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  description?: T;
  photos?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
        id?: T;
      };
  readiness?: T;
  propertyCount?: T;
  availablePropertyCount?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buildings_select".
 */
export interface BuildingsSelect<T extends boolean = true> {
  complex?: T;
  name?: T;
  yandexHouseId?: T;
  importOwnership?: T;
  section?: T;
  phase?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  floors?: T;
  readiness?: T;
  handoverAt?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers_select".
 */
export interface DevelopersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  origin?: T;
  feedSource?: T;
  externalId?: T;
  normalizedPhone?: T;
  phone?: T;
  email?: T;
  position?: T;
  bio?: T;
  photo?: T;
  status?: T;
  isPublished?: T;
  importHash?: T;
  lastSeenAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-sources_select".
 */
export interface FeedSourcesSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  market?: T;
  parser?: T;
  feedUrlRef?: T;
  credentialRef?: T;
  isEnabled?: T;
  priority?: T;
  fieldOwnership?: T;
  minOffersThresholdPercent?: T;
  maxOffersLimit?: T;
  schedule?: T;
  lastSuccessfulRunAt?: T;
  lastOfferCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  correlationId?: T;
  source?: T;
  mode?: T;
  status?: T;
  startedAt?: T;
  finishedAt?: T;
  total?: T;
  created?: T;
  updated?: T;
  unchanged?: T;
  skipped?: T;
  failed?: T;
  deactivated?: T;
  durationMs?: T;
  summary?: T;
  streamCompleted?: T;
  addressFormat?: T;
  deactivationAllowed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-issues_select".
 */
export interface ImportIssuesSelect<T extends boolean = true> {
  run?: T;
  severity?: T;
  externalId?: T;
  code?: T;
  message?: T;
  recordIndex?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  isEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskApplyLeadRetention".
 */
export interface TaskApplyLeadRetention {
  input: {
    retentionDays?: number | null;
  };
  output: {
    cutoff: string;
    processed: number;
    remaining: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskDeliverLead".
 */
export interface TaskDeliverLead {
  input: {
    deliveryId: string;
  };
  output: {
    status: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskImportFeed".
 */
export interface TaskImportFeed {
  input: {
    sourceId: string;
    mode: 'delta' | 'full_snapshot';
  };
  output: {
    runId: string;
    status: 'success' | 'suspicious';
    total: number;
    created: number;
    updated: number;
    unchanged: number;
    deactivated: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRecoverLeadDeliveries".
 */
export interface TaskRecoverLeadDeliveries {
  input?: unknown;
  output: {
    queued: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}