import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(path), 'utf8')

describe('Stage 5 operations contract', () => {
  it('keeps every reusable core area independent from project composition', () => {
    const cruiser = read('.dependency-cruiser.cjs')
    expect(cruiser).toContain("from: { path: '^src/core/' }")
    expect(cruiser).not.toContain("^src/core/(?!data-access/)")
  })

  it('builds a standalone artifact before deployment', () => {
    expect(read('next.config.ts')).toContain("output: 'standalone'")
    expect(read('package.json')).toContain('node .next/standalone/server.js')
    const pack = read('scripts/build-release-artifact.mjs')
    expect(pack).toContain(".next', 'standalone")
    expect(pack).toContain('clean exact origin/main')
    expect(pack).toContain("['diff', '--quiet', 'HEAD', '--']")
    expect(pack).toContain("['ls-files', '--others', '--exclude-standard']")
    expect(pack).toContain("standaloneRoot, '.next'")
    expect(pack).toContain("rmSync(path.join(bundleDir, '.next')")
    expect(pack).toContain('dereference: true')
    expect(pack).toContain("rebaseTracedModuleLinks(path.join(bundleDir, '.next', 'node_modules')")
    expect(pack).toContain('path.relative(path.dirname(entryPath), rebasedTarget)')
    expect(pack).toContain('value.name === identity.name && value.version === identity.version')
    expect(pack).toContain('candidates.sort((left, right) => left.localeCompare(right))[0]')
    expect(pack).not.toContain('cpSync(standaloneRoot, bundleDir')
    expect(pack).toContain('buildBeforeDeploy: true')
    expect(read('scripts/prepare-standalone.mjs')).toContain("'.env.production.local'")
    const ci = read('.sourcecraft/ci.yaml')
    const prCheck = ci.slice(ci.indexOf('  pr-check:'), ci.indexOf('  main-static-gate:'))
    const mainGate = ci.slice(ci.indexOf('  main-static-gate:'))
    expect(prCheck).toContain('pnpm verify')
    expect(prCheck).not.toContain('pnpm build')
    expect(mainGate).not.toContain('pnpm verify')
    expect(mainGate).toContain('pnpm build')
    expect(prCheck).toContain('git diff --exit-code -- src/payload-types.ts')
    expect(mainGate).toContain('git diff --exit-code -- src/payload-types.ts')
    expect(ci).toContain('.release-artifacts/release.part00')
    expect(ci).toContain('.release-artifacts/release.part09')
    expect(ci).toContain('.release-artifacts/release.json')
    expect(pack).toContain('const partBytes = 40 * 1024 * 1024')
    expect(pack).toContain('sha256: createHash')
  })

  it('installs without dependencies or a server-side build', () => {
    const installer = read('deploy/install-release.sh')
    expect(installer).not.toMatch(/pnpm install/)
    expect(installer).not.toMatch(/pnpm build/)
    expect(installer).toContain('node_modules/.bin/payload" migrate')
    expect(installer).toContain('src/payload/migrations-v2')
    expect(installer.indexOf('payload migrate')).toBeLessThan(installer.indexOf('current.next'))
    expect(installer).toContain('Embedded release SHA does not match requested SHA')
    expect(installer).toContain('Escaping release symlink')
    expect(installer).toContain('.release-verified')
    expect(installer).toContain('previous_verified_sha')
    expect(installer).toContain('chown -R root:"${APP_USER}" "${release_dir}"')
    expect(installer).toContain('find "${release_dir}" -type d -exec chmod 0750')
    expect(installer).toContain('runuser -u "${APP_RELEASE_USER}"')
    expect(installer).not.toContain('chown -R "${APP_USER}:${APP_USER}" "${release_dir}"')
    expect(read('deploy/bootstrap-server.sh')).toContain('-mindepth 1 -xdev ! -type l -exec chown root:"${APP_USER}"')
  })

  it('uses one private worker for all queues and schedules', () => {
    const worker = read('deploy/ams-realty-platform-starter-worker.service')
    const recovery = read('scripts/recover-orphaned-payload-jobs.mts')
    expect(worker).toContain('--all-queues --handle-schedules')
    expect(worker).toContain('current/node_modules/.bin/payload jobs:run')
    expect(worker).toContain('current/node_modules/.bin/tsx scripts/recover-orphaned-payload-jobs.mts')
    expect(worker).toContain('NODE_OPTIONS=--conditions=react-server')
    expect(worker).toContain('ProtectSystem=strict')
    expect(worker).toContain('ReadWritePaths=/opt/ams-realty-platform-starter/shared')
    expect(recovery).toContain('await payload.destroy()')
    expect(recovery).toContain('process.exit(0)')
  })

  it('keeps system outbox updates outside interactive document locks', () => {
    expect(read('src/core/data-access/system/leads/delivery.ts')).toContain('overrideLock: true')
    expect(read('src/core/data-access/system/leads/recovery.ts')).toContain('overrideLock: true')
  })

  it('ships an executable production owner bootstrap', () => {
    const packageJSON = JSON.parse(read('package.json'))
    expect(packageJSON.scripts['owner:bootstrap']).toContain('--conditions=react-server')
    expect(packageJSON.dependencies.tsx).toBe('4.22.4')
    expect(packageJSON.devDependencies.tsx).toBeUndefined()
  })

  it('enforces TLS and separate login, lead and public-read limits', () => {
    const nginx = read('deploy/nginx-internal.conf')
    expect(nginx).toContain('listen 127.0.0.1:8443 ssl')
    expect(nginx).toContain('zone=payload_login')
    expect(nginx).toContain('zone=public_leads')
    expect(nginx).toContain('zone=public_reads')
    expect(nginx).toContain('location ^~ /api/public/v1/')
    expect(nginx).toMatch(/location \^~ \/api\/ \{\s+return 403;/)
  })
})
