"use client";
import { ListChecks } from "lucide-react";
import { useEffect, useState } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "../../components/ui/accordion";

export type ArticleContentsItemDto = { id: string; title: string };

export function ArticleContentsView({ items, variant }: { items: ArticleContentsItemDto[]; variant: "mobile" | "sidebar" }) {
  const [progress, setProgress] = useState(0);
  const [activeId, setActiveId] = useState(items[0]?.id ?? "");
  useEffect(() => { if (variant !== "sidebar") return; const update = () => { const article = document.querySelector<HTMLElement>("[data-article-body]"); if (!article) return; const top = article.getBoundingClientRect().top + window.scrollY; setProgress(Math.min(100, Math.max(0, ((window.scrollY - top) / Math.max(article.scrollHeight - window.innerHeight, 1)) * 100))); let current = items[0]?.id ?? ""; for (const item of items) { const section = document.getElementById(item.id); if (section && section.getBoundingClientRect().top <= 180) current = item.id; } setActiveId(current); }; update(); window.addEventListener("scroll", update, { passive: true }); window.addEventListener("resize", update); return () => { window.removeEventListener("scroll", update); window.removeEventListener("resize", update); }; }, [items, variant]);
  if (variant === "mobile") return <Accordion type="single" collapsible defaultValue="contents" className="mt-5 rounded-lg border border-[var(--border)] bg-[var(--surface-card-soft)] p-4 lg:hidden"><AccordionItem value="contents" className="border-0"><AccordionTrigger className="p-0 text-body-compact leading-tight-copy" trailing={<span className="hidden" />}>Содержание статьи</AccordionTrigger><AccordionContent className="pb-0 pt-3"><ContentsList items={items} activeId="" mobile /></AccordionContent></AccordionItem></Accordion>;
  return <aside className="hidden lg:sticky lg:top-[136px] lg:block" aria-label="Содержание статьи"><div className="max-h-[calc(100vh-164px)] overflow-y-auto rounded-lg border border-[var(--border)] bg-[var(--surface-card)] p-5 shadow-[var(--journal-shadow-sidebar)] [scrollbar-width:thin]"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><ListChecks className="size-4" aria-hidden /></span><h2 className="text-body-large font-semibold leading-tight-copy">Содержание статьи</h2></div><div className="article-reading-progress mt-4 h-1.5 overflow-hidden rounded-full bg-[var(--journal-progress-track)]" role="progressbar" aria-label="Прогресс чтения статьи" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><div className="h-full rounded-full bg-[var(--accent)] transition-[width] duration-150" style={{ width: `${progress}%` }} /></div><nav className="mt-4" aria-label="Разделы материала"><ContentsList items={items} activeId={activeId} /></nav></div></aside>;
}

function ContentsList({ items, activeId, mobile = false }: { items: ArticleContentsItemDto[]; activeId: string; mobile?: boolean }) { if (!items.length) return <p className={mobile ? "text-support leading-step-body text-[var(--text-muted)]" : "rounded-lg bg-[var(--surface-card-soft)] p-3 text-support leading-step-body text-[var(--text-muted)]"}>Содержание появится после расширения материала разделами H2.</p>; return <ol className={mobile ? "grid gap-1.5" : "grid gap-1.5"}>{items.map((item, index) => <li key={item.id}><a href={`#${item.id}`} aria-current={activeId === item.id ? "true" : undefined} className={`grid grid-cols-[26px_minmax(0,1fr)] gap-2 rounded-lg px-3 py-2 text-support leading-step-body transition ${activeId === item.id ? "bg-[var(--accent-soft)] text-[var(--accent)]" : "bg-[var(--surface-card)] text-[var(--text-secondary)] hover:text-[var(--accent)]"}`}><span className="text-caption font-bold tabular-nums text-[var(--accent)]">{String(index + 1).padStart(2, "0")}</span><span>{item.title}</span></a></li>)}</ol>; }
