import type { JournalArticlePageDto } from "@starter/site-contracts";
import "../../styles/journal.css";
import { CalendarDays, Clock3 } from "lucide-react";
import type { ReactNode } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "../../components/ui/accordion";
import { RequestModalButton } from "../../components/shared/site-overlay-context";
import { Button } from "../../components/ui/button";
import { Card } from "../../components/ui/card";
import { Separator } from "../../components/ui/separator";
import type { SiteImageRenderer, SiteLinkRenderer } from "../../lib/adapters";
import { ArticleContentsView } from "../journal/ArticleContentsView";
import { ArticleDocumentView } from "../journal/ArticleDocumentView";
import { ArticleEditorialLinksView } from "../journal/ArticleEditorialLinksView";
import { JournalCarouselControlsView } from "../journal/JournalCarouselControlsView";
import { JournalBreadcrumbs } from "../journal/journal-shared";

export function JournalArticleView({ page, cityGenitive, linkRenderer: LinkRenderer, imageRenderer: ImageRenderer, renderActions, renderShowcaseCard, renderBottomNewBuildingCard }: {
  page: JournalArticlePageDto;
  cityGenitive: string;
  linkRenderer: SiteLinkRenderer;
  imageRenderer: SiteImageRenderer;
  renderActions: (variant: "desktop" | "mobile") => ReactNode;
  renderShowcaseCard: (index: number) => ReactNode;
  renderBottomNewBuildingCard: (index: number) => ReactNode;
}) {
  return <main className="bg-[var(--background)] px-5 pb-24 pt-6 text-[var(--journal-ink)] md:pb-32 md:pt-8"><div className="mx-auto max-w-site-frame">
    <JournalBreadcrumbs className="[scrollbar-width:none] [&::-webkit-scrollbar]:hidden" items={[{ label: "Главная", href: "/" }, { label: "Журнал агентства", href: "/journal" }, { label: page.topicLabel }]} linkRenderer={LinkRenderer} />
    <div className="mt-6 grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_300px] xl:gap-9 xl:grid-cols-[minmax(0,1fr)_320px]">
      <article data-article-body className="min-w-0 overflow-hidden rounded-lg bg-[var(--surface-card)]"><header className="p-5 md:p-6 lg:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-support font-medium leading-5 text-[var(--text-muted)]"><span className="inline-flex items-center gap-1.5"><CalendarDays className="size-4 text-[var(--accent)]" aria-hidden />{page.dateLabel}</span><span className="inline-flex items-center gap-1.5"><Clock3 className="size-4 text-[var(--accent)]" aria-hidden />{page.readingTimeLabel}</span></div>{renderActions("desktop")}</div>
        <h1 className="mt-5 max-w-202.5 text-editorial-title font-semibold leading-editorial-title text-[var(--text-primary)]">{page.article.title}</h1>
        <div className="mt-6 flex items-center gap-3"><span className="relative block size-13 overflow-hidden rounded-full bg-[var(--surface-muted)] ring-1 ring-[var(--border)]">{page.author.image ? <ImageRenderer src={page.author.image} alt={page.author.name} fill quality={95} className="origin-top scale-[1.72] object-cover object-[center_12%]" sizes="80px" /> : null}</span><span><span className="block text-body-compact font-semibold leading-5">{page.author.name}</span><span className="mt-0.5 block text-label leading-4 text-[var(--text-muted)]">{page.author.role}</span></span></div>
        <div data-article-cover className="relative mt-7 aspect-[16/8.6] overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--journal-surface-cover)]"><ImageRenderer src={page.cover.src} alt={page.cover.alt} fill priority unoptimized={page.cover.src.startsWith("/")} className="object-cover" sizes="(min-width:1280px) 980px, (min-width:1024px) calc(100vw - 380px), 100vw" /></div>
        {renderActions("mobile")}<ArticleContentsView items={page.contents} variant="mobile" />
      </header>
      <div className="px-5 pb-8 md:px-6 md:pb-9 lg:px-7 lg:pb-10"><ArticleDocumentView page={page} imageRenderer={ImageRenderer} renderShowcase={() => <TopicShowcase page={page} linkRenderer={LinkRenderer} renderCard={renderShowcaseCard} />} />
        <ArticleEditorialLinksView links={page.editorialLinks} variant="inline" linkRenderer={LinkRenderer} />
        {page.cta ? <section className="mt-10 max-w-185 overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--journal-surface-cta)] md:mt-11"><div className={`grid min-h-57.5 ${page.ctaImage ? 'md:grid-cols-[minmax(0,1fr)_240px] lg:grid-cols-[minmax(0,1fr)_280px]' : ''}`}><div className="flex flex-col justify-center p-5 md:p-6"><h2 className="max-w-[22ch] text-card-large font-semibold leading-card">{page.cta.title}</h2>{page.cta.text ? <p className="mt-3 max-w-[42ch] text-body leading-body text-[var(--text-secondary)]">{page.cta.text}</p> : null}<RequestModalButton type="button" request={{ title: page.cta.title, subtitle: page.cta.text, source: `journal:${page.article.slug}:cta`, formType: "journal_request" }} className="mt-5 w-fit">Получить консультацию</RequestModalButton></div>{page.ctaImage ? <div className="relative min-h-47.5 overflow-hidden md:min-h-full"><ImageRenderer src={page.ctaImage} alt="" fill className="object-cover" sizes="(min-width: 1280px) 300px, (min-width: 768px) 260px, 100vw" /><div className="absolute inset-0 bg-[var(--journal-cta-image-fade)]" /></div> : null}</div></section> : null}
        {page.footerLinks.length ? <div className="max-w-185"><ArticleEditorialLinksView links={page.footerLinks} variant="footer" linkRenderer={LinkRenderer} /></div> : null}
        {page.faq.length ? <section className="mt-10 max-w-185 md:mt-11" aria-labelledby="article-faq-title"><h2 id="article-faq-title" className="sr-only">Вопросы и ответы</h2><Accordion type="single" collapsible className="overflow-hidden rounded-lg border border-[var(--border)] bg-[var(--surface-card)]">{page.faq.map((item, index) => <AccordionItem key={item.question} value={`faq-${index}`} className="border-b-0 border-t first:border-t-0"><AccordionTrigger className="min-h-14.5 gap-5 px-5 py-3.5 text-body-compact leading-6 md:px-6">{item.question}</AccordionTrigger><AccordionContent className="px-5 pb-5 pr-12 text-body-compact leading-7 text-[var(--journal-copy-soft)] md:px-6 md:pr-14">{item.answer}</AccordionContent></AccordionItem>)}</Accordion></section> : null}
      </div></article><ArticleContentsView items={page.contents} variant="sidebar" />
    </div><BottomSections page={page} cityGenitive={cityGenitive} linkRenderer={LinkRenderer} imageRenderer={ImageRenderer} renderCard={renderBottomNewBuildingCard} />
  </div></main>;
}

function TopicShowcase({ page, linkRenderer: LinkRenderer, renderCard }: { page: JournalArticlePageDto; linkRenderer: SiteLinkRenderer; renderCard: (index: number) => ReactNode }) { const showcase = page.showcase; if (!showcase?.items.length) return null; return <section className="my-10" aria-labelledby="article-topic-showcase-title"><Separator /><div className="py-7 md:py-8"><div className="flex items-center justify-between gap-4"><h2 id="article-topic-showcase-title" className="text-heading-medium font-semibold leading-heading">Вас может заинтересовать</h2><LinkRenderer href={showcase.action.href} className="hidden shrink-0 text-support font-semibold text-[var(--text-secondary)] hover:text-[var(--accent)] sm:inline-flex">{showcase.action.label}</LinkRenderer></div><div className="mt-5 grid gap-5 md:grid-cols-3">{showcase.items.map((_, index) => renderCard(index))}</div><Button asChild variant="outline" className="mt-5 w-full sm:hidden"><LinkRenderer href={showcase.action.href}>{showcase.action.label}</LinkRenderer></Button></div><Separator /></section>; }

function BottomSections({ page, cityGenitive, linkRenderer: LinkRenderer, imageRenderer: ImageRenderer, renderCard }: { page: JournalArticlePageDto; cityGenitive: string; linkRenderer: SiteLinkRenderer; imageRenderer: SiteImageRenderer; renderCard: (index: number) => ReactNode }) { return <div className="mt-10 grid gap-8 md:mt-12 md:gap-10">{page.relatedArticles.length ? <Card className="overflow-hidden border-0 p-5 md:p-6 lg:p-7"><div className="flex items-center justify-between gap-4"><h2 className="text-heading-compact font-semibold leading-tight md:text-section-base">Больше статей о недвижимости</h2><JournalCarouselControlsView targetId="journal-more-articles-track" /></div><div id="journal-more-articles-track" className="mt-7 flex snap-x gap-6 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{page.relatedArticles.map((item) => <div key={item.id} className="min-w-0 flex-[0_0_82%] snap-start sm:flex-[0_0_285px] md:flex-[0_0_300px]"><LinkRenderer href={item.href} className="group block min-w-0"><span className="relative block aspect-[16/10] overflow-hidden rounded-lg bg-[var(--surface-muted)]"><ImageRenderer src={item.image} alt="" fill unoptimized={item.image.startsWith("/")} sizes="(min-width: 1280px) 300px, (min-width: 640px) 285px, 82vw" className="object-cover transition duration-500 group-hover:scale-[1.03]" /></span><h3 className="mt-3 line-clamp-2 text-body-compact font-semibold leading-5 transition group-hover:text-[var(--accent)]">{item.title}</h3><span className="mt-2 block text-caption leading-4 text-[var(--text-muted)]">{item.dateLabel}</span></LinkRenderer></div>)}</div></Card> : null}{page.relatedNewBuildings.length ? <Card className="overflow-hidden border-0 p-5 md:p-6 lg:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center justify-between gap-4 sm:flex-1"><h2 className="text-heading-compact font-semibold leading-tight md:text-section-base">Вас может заинтересовать</h2><JournalCarouselControlsView targetId="journal-new-buildings-track" /></div><Button asChild className="h-auto min-h-10"><LinkRenderer href="/novostroyki">Все новостройки {cityGenitive}</LinkRenderer></Button></div><div id="journal-new-buildings-track" className="mt-7 flex snap-x gap-6 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{page.relatedNewBuildings.map((_, index) => <div key={page.relatedNewBuildings[index]!.id} className="min-w-0 flex-[0_0_88%] snap-start sm:flex-[0_0_320px] lg:flex-[0_0_300px] xl:flex-[0_0_315px]">{renderCard(index)}</div>)}</div></Card> : null}</div>; }
